Repository 42organization/42gg.server.dev.v2, pull requests merged in 2023-12, with the labels that each got.

#325 :sparkles: [Feature] 관리자 토너먼트 유저 추가 API 추가
  src/main/java/com/gg/server/admin/tournament/controller/TournamentAdminController.java
  src/main/java/com/gg/server/admin/tournament/dto/TournamentAdminAddUserRequestDto.java
  src/main/java/com/gg/server/admin/tournament/dto/TournamentAdminAddUserResponseDto.java
  src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java
  src/main/java/com/gg/server/domain/tournament/data/Tournament.java
  src/main/java/com/gg/server/domain/tournament/data/TournamentUserRepository.java
  src/test/java/com/gg/server/admin/tournament/controller/TournamentAdminControllerTest.java
  src/test/java/com/gg/server/admin/tournament/service/TournamentAdminServiceTest.java
  src/test/java/com/gg/server/utils/TestDataUtils.java
Labels: enhancement

#327 ✨ [Feature] 관리자 tournament 생성 API 추가
  src/main/java/com/gg/server/admin/tournament/controller/TournamentAdminController.java
  src/main/java/com/gg/server/admin/tournament/dto/TournamentAdminCreateRequestDto.java
  src/main/java/com/gg/server/admin/tournament/exception/TournamentTitleConflictException.java
  src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java
  src/main/java/com/gg/server/domain/tournament/controller/TournamentController.java
  src/main/java/com/gg/server/domain/tournament/data/Tournament.java
  src/main/java/com/gg/server/domain/tournament/data/TournamentRepository.java
  src/main/java/com/gg/server/global/exception/ErrorCode.java
  src/test/java/com/gg/server/admin/tournament/controller/TournamentAdminControllerTest.java
  src/test/java/com/gg/server/admin/tournament/service/TournamentAdminServiceTest.java
  src/test/java/com/gg/server/utils/TestDataUtils.java
Labels: enhancement

#345 ✨ [Feature] 토너먼트 유저 조회 API 추가
  src/main/java/com/gg/server/admin/tournament/controller/TournamentAdminController.java
  src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java
  src/main/java/com/gg/server/domain/tournament/data/TournamentUserRepository.java
  src/main/java/com/gg/server/domain/tournament/dto/TournamentUserListResponseDto.java
  src/main/java/com/gg/server/domain/tournament/dto/TournamentUserResponseDto.java
  src/test/java/com/gg/server/admin/tournament/controller/TournamentAdminUserControllerTest.java
  src/test/java/com/gg/server/utils/TestDataUtils.java
Labels: enhancement

#352 🔨 [Refactor] Cascade 추가
  src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java
  src/main/java/com/gg/server/domain/tournament/data/Tournament.java
  src/main/resources/db/migration/V3__migration_42gg_5th.sql
  src/test/java/com/gg/server/admin/tournament/service/TournamentAdminServiceTest.java
Labels: refactoring

#354 🔨 [Refactor] 관리자 토너먼트 유저 추가 & 삭제 서비스 로직 리팩토링
  src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java
  src/test/java/com/gg/server/admin/tournament/service/TournamentAdminServiceTest.java
Labels: refactoring

#358 ✨ [Feature] 토너먼트 Id에 해당하는 게임 전체 조회 api 추가
  src/main/java/com/gg/server/domain/game/data/GameRepository.java
  src/main/java/com/gg/server/domain/game/dto/GameResultResDto.java
  src/main/java/com/gg/server/domain/team/dto/TeamUserListDto.java
  src/main/java/com/gg/server/domain/tournament/controller/TournamentController.java
  src/main/java/com/gg/server/domain/tournament/data/TournamentGameRepository.java
  src/main/java/com/gg/server/domain/tournament/dto/TournamentGameListResponseDto.java
  src/main/java/com/gg/server/domain/tournament/dto/TournamentGameResDto.java
  src/main/java/com/gg/server/domain/tournament/service/TournamentService.java
  src/main/java/com/gg/server/domain/tournament/type/TournamentRound.java
  src/test/java/com/gg/server/domain/tournament/controller/TournamentFindControllerTest.java
  src/test/java/com/gg/server/domain/tournament/controller/TournamentGameControllerTest.java
  src/test/java/com/gg/server/utils/TestDataUtils.java
Labels: enhancement

#357 ✨ [Feature] 토너먼트 추가로 인한 Match 로직 수정
  src/main/java/com/gg/server/admin/game/controller/GameAdminController.java
  src/main/java/com/gg/server/domain/match/controller/MatchController.java
  src/main/java/com/gg/server/domain/match/service/MatchFindService.java
  src/main/java/com/gg/server/domain/match/service/MatchService.java
  src/main/java/com/gg/server/domain/match/type/Option.java
  src/main/java/com/gg/server/domain/match/utils/SlotGenerator.java
  src/main/java/com/gg/server/domain/tournament/data/Tournament.java
  src/main/java/com/gg/server/domain/tournament/exception/TournamentConflictException.java
  src/main/java/com/gg/server/domain/tournament/service/TournamentService.java
  src/main/java/com/gg/server/domain/tournament/type/TournamentType.java
  src/test/java/com/gg/server/domain/match/service/MatchServiceTest.java
  src/test/java/com/gg/server/domain/match/service/MatchTestUtils.java
Labels: enhancement, refactoring

#363 :sparkles: [Feature] 토너먼트 유저 참가 신청 취소 API
  src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java
  src/main/java/com/gg/server/domain/tournament/controller/TournamentController.java
  src/main/java/com/gg/server/domain/tournament/service/TournamentService.java
  src/test/java/com/gg/server/admin/tournament/service/TournamentAdminServiceTest.java
  src/test/java/com/gg/server/domain/tournament/controller/TournamentFindControllerTest.java
  src/test/java/com/gg/server/domain/tournament/service/TournamentServiceTest.java
Labels: enhancement

#359 🐛 [Fix] 기존 통합 테스트코드 수리
  src/main/java/com/gg/server/admin/game/dto/RankGamePPPModifyReqDto.java
  src/main/java/com/gg/server/admin/noti/dto/NotiAdminDto.java
  src/main/java/com/gg/server/admin/user/dto/UserSearchAdminResponseDto.java
  src/main/java/com/gg/server/domain/game/data/Game.java
  src/main/java/com/gg/server/domain/match/service/MatchService.java
  src/main/java/com/gg/server/domain/rank/dto/ExpRankDto.java
  src/main/java/com/gg/server/domain/rank/dto/ExpRankPageResponseDto.java
  src/main/java/com/gg/server/domain/team/data/Team.java
  src/main/java/com/gg/server/domain/team/data/TeamUser.java
  src/main/java/com/gg/server/domain/tier/data/TierRepository.java
  src/main/java/com/gg/server/domain/user/dto/UserLiveResponseDto.java
  src/main/java/com/gg/server/domain/user/dto/UserModifyRequestDto.java
  src/main/java/com/gg/server/domain/user/dto/UserRankResponseDto.java
  src/test/java/com/gg/server/admin/announcement/controller/AnnouncementAdminControllerTest.java
  src/test/java/com/gg/server/admin/coin/controller/CoinPolicyAdminControllerTest.java
  src/test/java/com/gg/server/admin/feedback/controller/FeedbackAdminControllerTest.java
  src/test/java/com/gg/server/admin/game/controller/GameAdminControllerTest.java
  src/test/java/com/gg/server/admin/item/controller/ItemAdminControllerTest.java
  src/test/java/com/gg/server/admin/megaphone/controller/MegaphoneAdminControllerTest.java
  src/test/java/com/gg/server/admin/penalty/controller/PenaltyAdminControllerTest.java
  src/test/java/com/gg/server/admin/receipt/controller/ReceiptAdminControllerTest.java
  src/test/java/com/gg/server/admin/season/SeasonAdminControllerTest.java
  src/test/java/com/gg/server/admin/slotmanagement/controller/SlotAdminControllerFailTest.java
  src/test/java/com/gg/server/admin/slotmanagement/controller/SlotAdminControllerTest.java
  src/test/java/com/gg/server/admin/user/controller/UserAdminControllerTest.java
  src/test/java/com/gg/server/config/TestRedisConfig.java
  src/test/java/com/gg/server/domain/announcement/controller/AnnouncementControllerTest.java
  src/test/java/com/gg/server/domain/coin/service/CoinHistoryServiceTest.java
  src/test/java/com/gg/server/domain/coin/service/UserCoinChangeServiceTest.java
  src/test/java/com/gg/server/domain/game/GameControllerTest.java
  src/test/java/com/gg/server/domain/game/service/GameDBTest.java
  src/test/java/com/gg/server/domain/game/service/GameFindServiceTest.java
  src/test/java/com/gg/server/domain/game/service/GameServiceTest.java
  src/test/java/com/gg/server/domain/game/service/GameStatusServiceTest.java
  src/test/java/com/gg/server/domain/match/service/MatchBothServiceTest.java
  src/test/java/com/gg/server/domain/match/service/MatchServiceTest.java
  src/test/java/com/gg/server/domain/megaphone/controller/MegaphoneControllerTest.java
  src/test/java/com/gg/server/domain/noti/controller/NotiControllerTest.java
  src/test/java/com/gg/server/domain/rank/controller/RankControllerTest.java
  src/test/java/com/gg/server/domain/season/SeasonTriggerTest.java
  src/test/java/com/gg/server/domain/tournament/controller/TournamentGameControllerTest.java
  src/test/java/com/gg/server/domain/user/controller/UserControllerTest.java
  src/test/java/com/gg/server/utils/ItemTestUtils.java
  src/test/java/com/gg/server/utils/TestDataUtils.java
  src/test/resources/application.yml
  src/test/resources/schema.sql
Labels: bug

#369 ✨ [Feature] 토너먼트 첫 경기 매칭하는 Scheduler 생성
  src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java
  src/main/java/com/gg/server/domain/game/data/Game.java
  src/main/java/com/gg/server/domain/match/service/GameUpdateService.java
  src/main/java/com/gg/server/domain/team/data/Team.java
  src/main/java/com/gg/server/domain/tournament/data/Tournament.java
  src/main/java/com/gg/server/domain/tournament/data/TournamentGame.java
  src/main/java/com/gg/server/domain/tournament/data/TournamentRepository.java
  src/main/java/com/gg/server/domain/tournament/data/TournamentUser.java
  src/main/java/com/gg/server/domain/tournament/service/TournamentService.java
  src/main/java/com/gg/server/domain/tournament/type/TournamentRound.java
  src/main/java/com/gg/server/global/scheduler/TournamentScheduler.java
  src/test/java/com/gg/server/domain/tournament/controller/TournamentFindControllerTest.java
  src/test/java/com/gg/server/domain/tournament/controller/TournamentSchedulerTest.java
  src/test/java/com/gg/server/utils/TestDataUtils.java
Labels: enhancement

#376 🔨 [Refactor] 토너먼트 생성 및 수정 매서드 추가 및 수정
  src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java
  src/main/java/com/gg/server/domain/game/data/GameRepository.java
  src/main/java/com/gg/server/domain/tournament/data/TournamentRepository.java
  src/test/java/com/gg/server/admin/tournament/controller/TournamentAdminControllerTest.java
  src/test/java/com/gg/server/admin/tournament/service/TournamentAdminServiceTest.java
  src/test/java/com/gg/server/domain/tournament/service/TournamentServiceTest.java
Labels: enhancement, refactoring

#371 ✨ [Feature] 토너먼트 게임 결과 등록 API 추가
  src/main/java/com/gg/server/domain/game/GameController.java
  src/main/java/com/gg/server/domain/game/dto/request/GameListReqDto.java
  src/main/java/com/gg/server/domain/game/dto/request/NormalGameListReqDto.java
  src/main/java/com/gg/server/domain/game/dto/request/NormalResultReqDto.java
  src/main/java/com/gg/server/domain/game/dto/request/RankGameListReqDto.java
  src/main/java/com/gg/server/domain/game/dto/request/RankResultReqDto.java
  src/main/java/com/gg/server/domain/game/dto/request/TournamentResultReqDto.java
  src/main/java/com/gg/server/domain/game/exception/GameAlreadyExistException.java
  src/main/java/com/gg/server/domain/game/exception/GameStatusNotMatchedException.java
  src/main/java/com/gg/server/domain/game/exception/ScoreAlreadyEnteredException.java
  src/main/java/com/gg/server/domain/game/service/GameService.java
  src/main/java/com/gg/server/domain/team/exception/TeamIdNotMatchException.java
  src/main/java/com/gg/server/domain/tournament/data/TournamentGameRepository.java
  src/main/java/com/gg/server/global/exception/ErrorCode.java
  src/main/java/com/gg/server/global/exception/GlobalExceptionHandler.java
  src/test/java/com/gg/server/admin/game/controller/GameAdminControllerTest.java
  src/test/java/com/gg/server/domain/game/GameControllerTest.java
  src/test/java/com/gg/server/domain/game/service/GameServiceTest.java
  src/test/java/com/gg/server/domain/user/controller/UserControllerTest.java
  src/test/java/com/gg/server/utils/TestDataUtils.java
Labels: bug, enhancement

#380 ✨ [Feature] 토너먼트 게임 결과 수정 api 추가
  src/main/java/com/gg/server/admin/tournament/controller/TournamentAdminController.java
  src/main/java/com/gg/server/admin/tournament/dto/TournamentGameUpdateRequestDto.java
  src/main/java/com/gg/server/admin/tournament/exception/TournamentNotLiveException.java
  src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java
  src/main/java/com/gg/server/domain/game/data/GameRepository.java
  src/main/java/com/gg/server/domain/game/exception/ScoreNotInvalidException.java
  src/main/java/com/gg/server/domain/team/dto/TeamReqDto.java
  src/main/java/com/gg/server/domain/tournament/exception/TournamentGameNotFoundException.java
  src/main/java/com/gg/server/domain/tournament/exception/TournamentNotFoundException.java
  src/main/java/com/gg/server/domain/tournament/exception/TournamentUpdateException.java
  src/main/java/com/gg/server/global/exception/ErrorCode.java
  src/test/java/com/gg/server/admin/tournament/controller/TournamentAdminControllerTest.java
  src/test/java/com/gg/server/utils/TestDataUtils.java
Labels: enhancement

#384 🐛 [ Fix] findTournamentGameTest 테스트 코드 수정 및 TestDataUtils 매서드 수정
  src/test/java/com/gg/server/domain/tournament/controller/TournamentGameControllerTest.java
  src/test/java/com/gg/server/utils/TestDataUtils.java
Labels: bug

#383 ✨ [Feature] 토너먼트 유저 참가 신청 API
  src/main/java/com/gg/server/admin/tournament/dto/TournamentAdminAddUserResponseDto.java
  src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java
  src/main/java/com/gg/server/domain/tournament/controller/TournamentController.java
  src/main/java/com/gg/server/domain/tournament/data/TournamentUserRepository.java
  src/main/java/com/gg/server/domain/tournament/service/TournamentService.java
  src/test/java/com/gg/server/domain/tournament/controller/TournamentFindControllerTest.java
  src/test/java/com/gg/server/domain/tournament/service/TournamentServiceTest.java
Labels: enhancement

#397 [FIX] #394 refresh token create logic fix
  src/main/java/com/gg/server/global/security/handler/OAuthAuthenticationSuccessHandler.java
  src/main/java/com/gg/server/global/security/jwt/utils/AuthTokenProvider.java
Labels: bug

#390 ✨ [Feature] 토너먼트 연관관계 메서드 처리
  src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java
  src/main/java/com/gg/server/domain/game/data/Game.java
  src/main/java/com/gg/server/domain/team/data/Team.java
  src/main/java/com/gg/server/domain/tournament/data/Tournament.java
  src/main/java/com/gg/server/domain/tournament/data/TournamentGame.java
  src/main/java/com/gg/server/domain/tournament/data/TournamentUser.java
  src/main/java/com/gg/server/domain/tournament/service/TournamentService.java
  src/main/java/com/gg/server/global/exception/ErrorCode.java
  src/main/java/com/gg/server/global/exception/custom/BusinessException.java
  src/main/java/com/gg/server/global/exception/custom/CustomRuntimeException.java
  src/main/java/com/gg/server/global/utils/BusinessChecker.java
  src/test/java/com/gg/server/admin/tournament/controller/TournamentAdminControllerTest.java
  src/test/java/com/gg/server/admin/tournament/service/TournamentAdminServiceTest.java
  src/test/java/com/gg/server/domain/game/data/GameUnitTest.java
  src/test/java/com/gg/server/domain/team/data/TeamUnitTest.java
  src/test/java/com/gg/server/domain/tournament/controller/TournamentSchedulerTest.java
  src/test/java/com/gg/server/domain/tournament/data/TournamentUnitTest.java
  src/test/java/com/gg/server/domain/tournament/service/TournamentServiceTest.java
  src/test/java/com/gg/server/utils/ReflectionUtilsForUnitTest.java
  src/test/java/com/gg/server/utils/TestDataUtils.java
  src/test/resources/schema.sql
Labels: enhancement

#393 [Refactoring] return 패턴 responseEntity 빌더 형식으로 수정
  src/main/java/com/gg/server/admin/tournament/controller/TournamentAdminController.java
  src/main/java/com/gg/server/admin/tournament/dto/TournamentGameUpdateRequestDto.java
  src/main/java/com/gg/server/domain/tournament/controller/TournamentController.java
  src/main/java/com/gg/server/domain/tournament/dto/TournamentFilterRequestDto.java
  src/main/java/com/gg/server/domain/tournament/service/TournamentService.java
  src/main/java/com/gg/server/domain/tournament/validation/EnumValue.java
  src/main/java/com/gg/server/domain/tournament/validation/ValueOfEnumValidator.java
  src/main/java/com/gg/server/global/exception/GlobalExceptionHandler.java
  src/test/java/com/gg/server/domain/tournament/controller/TournamentFindControllerTest.java
Labels: refactoring

#391 🔨 [Refactoring] 개발 서버 ci/cd 설정
  .github/workflows/test-code-validation.yml
  .github/workflows/test-deploy.yml
  .github/workflows/test-migrate-deploy.yml
  update-main-yml.sh
  update-test-yml.sh
Labels: enhancement, refactoring

#389 🔨 [Refactor] Exception 수정 및 병합
  src/main/java/com/gg/server/admin/tournament/exception/TournamentNotLiveException.java
  src/main/java/com/gg/server/admin/tournament/exception/TournamentTitleConflictException.java
  src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java
  src/main/java/com/gg/server/domain/tournament/exception/TournamentConflictException.java
  src/main/java/com/gg/server/domain/tournament/exception/TournamentGameNotFoundException.java
  src/main/java/com/gg/server/domain/tournament/exception/TournamentNotFoundException.java
  src/main/java/com/gg/server/domain/tournament/exception/TournamentUpdateException.java
  src/main/java/com/gg/server/domain/tournament/service/TournamentService.java
  src/main/java/com/gg/server/global/exception/ErrorCode.java
  src/test/java/com/gg/server/admin/tournament/controller/TournamentAdminControllerTest.java
  src/test/java/com/gg/server/admin/tournament/service/TournamentAdminServiceTest.java
Labels: refactoring

#404 ✨ [Feature] 토너먼트 게임 매칭 로직 추가
  src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java
  src/main/java/com/gg/server/domain/game/data/Game.java
  src/main/java/com/gg/server/domain/game/service/GameService.java
  src/main/java/com/gg/server/domain/match/exception/WinningTeamNotFoundException.java
  src/main/java/com/gg/server/domain/match/service/MatchTournamentService.java
  src/main/java/com/gg/server/domain/match/type/TournamentMatchStatus.java
  src/main/java/com/gg/server/domain/match/utils/SlotGenerator.java
  src/main/java/com/gg/server/domain/team/data/TeamUser.java
  src/main/java/com/gg/server/domain/team/exception/TeamIdNotMatchException.java
  src/main/java/com/gg/server/domain/team/exception/TeamNotFoundException.java
  src/main/java/com/gg/server/domain/tournament/data/Tournament.java
  src/main/java/com/gg/server/domain/tournament/data/TournamentGameRepository.java
  src/main/java/com/gg/server/domain/tournament/exception/TournamentGameNotFoundException.java
  src/main/java/com/gg/server/domain/tournament/service/TournamentService.java
  src/main/java/com/gg/server/domain/tournament/type/TournamentRound.java
  src/main/java/com/gg/server/domain/tournament/type/TournamentStatus.java
  src/main/java/com/gg/server/domain/tournament/type/TournamentType.java
  src/main/java/com/gg/server/domain/tournament/type/TournamentUserStatus.java
  src/main/java/com/gg/server/global/exception/ErrorCode.java
  src/main/java/com/gg/server/global/scheduler/TournamentScheduler.java
  src/test/java/com/gg/server/admin/tournament/controller/TournamentAdminControllerTest.java
  src/test/java/com/gg/server/domain/game/GameControllerTest.java
  src/test/java/com/gg/server/domain/match/service/MatchBothServiceTest.java
  src/test/java/com/gg/server/domain/match/service/MatchServiceTest.java
  src/test/java/com/gg/server/domain/match/service/MatchTestUtils.java
  src/test/java/com/gg/server/domain/match/service/MatchTournamentTest.java
  src/test/java/com/gg/server/utils/MatchTestUtils.java
  src/test/java/com/gg/server/utils/TestDataUtils.java
Labels: enhancement, refactoring

#402 [FIX] Admin 게임 점수 수정 시 승패 카운트 오류 수정
  src/main/java/com/gg/server/admin/game/service/GameAdminService.java
  src/main/java/com/gg/server/domain/rank/redis/RankRedisService.java
  src/main/java/com/gg/server/domain/team/data/TeamUserRepository.java
Labels: bug

#407 🔨 [Refactor] 토너먼트 생성 및 수정 시간 검증 로직 수정
  src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java
  src/test/java/com/gg/server/admin/tournament/controller/TournamentAdminControllerTest.java
  src/test/java/com/gg/server/admin/tournament/service/TournamentAdminServiceTest.java
  src/test/java/com/gg/server/utils/TestDataUtils.java
Labels: refactoring

#411 💚 [Chore] 토너먼트 제목 중복 체크 제거
  src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java
  src/main/java/com/gg/server/domain/tournament/data/TournamentRepository.java
  src/main/java/com/gg/server/global/exception/ErrorCode.java
  src/test/java/com/gg/server/admin/tournament/controller/TournamentAdminControllerTest.java
  src/test/java/com/gg/server/admin/tournament/service/TournamentAdminServiceTest.java
Labels: refactoring

#415 🐛 [Fix] 토너먼트 게임 결과 등록할 때 pchange 생성 안 되는 문제 해결
  src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java
  src/main/java/com/gg/server/domain/game/GameController.java
  src/main/java/com/gg/server/domain/game/service/GameService.java
  src/test/java/com/gg/server/admin/tournament/controller/TournamentAdminControllerTest.java
  src/test/java/com/gg/server/domain/game/GameControllerTest.java
Labels: bug

#414 🐛 [Fix] 토너먼트 시간에 매칭 block 에러 수정
  src/main/java/com/gg/server/domain/match/service/MatchService.java
  src/main/java/com/gg/server/domain/match/utils/SlotGenerator.java
  src/test/java/com/gg/server/domain/match/service/MatchServiceTest.java
Labels: bug

#410 🐛 [Fix] 관리자 게임 전체 조회에서 토너먼트 보이는 문제
  src/main/java/com/gg/server/admin/game/data/GameAdminRepository.java
  src/main/java/com/gg/server/admin/game/service/GameAdminService.java
  src/main/java/com/gg/server/domain/pchange/data/PChangeRepository.java
  src/test/java/com/gg/server/admin/game/controller/GameAdminControllerTest.java
Labels: bug, refactoring

#427 ✨ [Feature] 토너먼트 종료시 endTime 갱신 로직 추가
  src/main/java/com/gg/server/domain/match/service/MatchTournamentService.java
  src/main/java/com/gg/server/domain/tournament/data/Tournament.java
  src/test/java/com/gg/server/domain/match/service/MatchTournamentTest.java
Labels: enhancement

#430 🐛 [Fix] 메인 페이지에서 토너먼트 게임 취소 동작 방어
  src/main/java/com/gg/server/domain/match/service/MatchService.java
  src/main/java/com/gg/server/global/exception/ErrorCode.java
  src/test/java/com/gg/server/domain/match/service/MatchServiceTest.java
Labels: bug

#433 :bug: [Fix] 토너먼트 첫 8강 게임 진행시간 문제 수정
  src/main/java/com/gg/server/domain/match/service/MatchTournamentService.java
  src/test/java/com/gg/server/domain/match/service/MatchTournamentTest.java
Labels: bug

#425 ✨[Feature] 게임 결과 조회 api 통합
  src/main/java/com/gg/server/domain/game/GameController.java
  src/main/java/com/gg/server/domain/game/dto/GamePChangeResultResDto.java
  src/main/java/com/gg/server/domain/game/dto/GamePPPChangeResultResDto.java
  src/main/java/com/gg/server/domain/game/service/GameService.java
  src/main/java/com/gg/server/global/exception/GlobalExceptionHandler.java
  src/test/java/com/gg/server/domain/game/GameControllerTest.java
Labels: enhancement

#442 🔨 [Refactor] 토너먼트에 경우 isImminent true로 전달
  src/main/java/com/gg/server/domain/match/dto/MatchStatusDto.java
  src/test/java/com/gg/server/domain/match/dto/MatchStatusDtoUnitTest.java
Labels: enhancement

#438 🐛 [Fix] findPChangeByGameId optional 버그 수정
  src/main/java/com/gg/server/domain/game/service/GameService.java
  src/main/java/com/gg/server/domain/pchange/data/PChangeRepository.java
Labels: bug

#417 🔨 [Refactor] main merge 전 dev 브랜치 수정사항
  src/main/java/com/gg/server/admin/tournament/dto/TournamentAdminAddUserResponseDto.java
  src/main/java/com/gg/server/domain/game/data/GameRepository.java
  src/main/java/com/gg/server/domain/tournament/data/Tournament.java
  src/main/java/com/gg/server/domain/tournament/dto/TournamentResponseDto.java
  src/main/java/com/gg/server/domain/tournament/service/TournamentService.java
  src/main/java/com/gg/server/global/exception/ErrorCode.java
  src/test/java/com/gg/server/domain/game/GameControllerTest.java
  src/test/java/com/gg/server/domain/tournament/controller/TournamentFindControllerTest.java
Labels: refactoring

#446 🐛 [Fix] 잘못된 Positive에 대한 import 수정
  src/main/java/com/gg/server/admin/tournament/controller/TournamentAdminController.java
  src/main/java/com/gg/server/domain/game/dto/request/TournamentResultReqDto.java
  src/main/java/com/gg/server/domain/tournament/controller/TournamentController.java
Labels: bug

#454 ✨ [Feat] deploy 프로메테우스 추가
  .github/workflows/main-deploy.yml
  .github/workflows/test-deploy.yml
Labels: enhancement

#456 :bug: [Fix] 토너먼트 LIVE 상태에서도 신청 삭제 되는 이슈
  src/main/java/com/gg/server/domain/tournament/service/TournamentService.java
Labels: bug

#435 🧪 [Unit Test] 토너먼트 updateEndTime 매서드 유닛 테스트 추가 및 기존 테스트 코드 수정
  src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java
  src/test/java/com/gg/server/admin/tournament/service/TournamentAdminServiceTest.java
  src/test/java/com/gg/server/domain/tournament/data/TournamentUnitTest.java
  src/test/java/com/gg/server/domain/tournament/service/TournamentServiceTest.java
  src/test/java/com/gg/server/utils/ReflectionUtilsForUnitTest.java
Labels: test
