Repository 42organization/42gg.server.dev.v2, pull requests merged in 2023-11, with the labels that each got.

#300 ✨ [Feature] Tournament entity repository 생성
  src/main/java/com/gg/server/domain/touranment/data/Tournament.java
  src/main/java/com/gg/server/domain/touranment/data/TournamentGame.java
  src/main/java/com/gg/server/domain/touranment/data/TournamentGameRepository.java
  src/main/java/com/gg/server/domain/touranment/data/TournamentRepository.java
  src/main/java/com/gg/server/domain/touranment/data/TournamentUser.java
  src/main/java/com/gg/server/domain/touranment/data/TournamentUserRepository.java
  src/main/java/com/gg/server/domain/touranment/type/TournamentRound.java
  src/main/java/com/gg/server/domain/touranment/type/TournamentStatus.java
  src/main/java/com/gg/server/domain/touranment/type/TournamentType.java
Labels: enhancement

#305 🔨 [Refactor] Tournament 정적 팩토리 메서드 of 추가
  src/main/java/com/gg/server/domain/tournament/data/Tournament.java
Labels: refactoring

#306 ✨ [Feature] tournament 테이블 초기화 SQL 추가
  src/main/java/com/gg/server/domain/tournament/data/Tournament.java
  src/main/java/com/gg/server/domain/tournament/data/TournamentGame.java
  src/main/resources/db/migration/V3__migration_42gg_5th.sql
Labels: enhancement, refactoring

#311 🔨 [Refactor] 토너먼트 FK constraint NO ACTION으로 수정
  src/main/resources/db/migration/V3__migration_42gg_5th.sql
Labels: refactoring

#313 :sparkles: [Feature] 토너먼트 생성, 수정 exception 추가
  src/main/java/com/gg/server/domain/tournament/exception/TournamentConflictException.java
  src/main/java/com/gg/server/domain/tournament/exception/TournamentNotFoundException.java
  src/main/java/com/gg/server/domain/tournament/exception/TournamentUpdateException.java
  src/main/java/com/gg/server/global/exception/ErrorCode.java
Labels: enhancement

#315 :hammer: [Refactor] 토너먼트, 토너먼트 게임 테이블 수정
  src/main/java/com/gg/server/domain/tournament/data/Tournament.java
  src/main/java/com/gg/server/domain/tournament/data/TournamentGame.java
  src/main/resources/db/migration/V3__migration_42gg_5th.sql
Labels: enhancement

#316 :bug: [Fix] tournament 관련 테이블의 varchar 길이 수정
  src/main/resources/db/migration/V3__migration_42gg_5th.sql
Labels: bug, enhancement

#314 ✨ [Feature] Tournament 수정 API 추가
  src/main/java/com/gg/server/admin/tournament/controller/TournamentAdminController.java
  src/main/java/com/gg/server/admin/tournament/dto/TournamentAdminUpdateRequestDto.java
  src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java
  src/main/java/com/gg/server/domain/tournament/data/Tournament.java
  src/main/java/com/gg/server/domain/tournament/data/TournamentRepository.java
  src/test/java/com/gg/server/admin/tournament/controller/TournamentAdminControllerTest.java
  src/test/java/com/gg/server/admin/tournament/service/TournamentAdminServiceTest.java
  src/test/java/com/gg/server/utils/TestDataUtils.java
Labels: enhancement

#320 ✨ feat: 마이그레이션 테스트 서버 배포용 github action 추가
  .github/workflows/test-migrate-deploy.yml
Labels: enhancement

#324 🐛 [Fix] ConfigureRedisAction Bean 추가
  src/main/java/com/gg/server/global/config/RedisConfig.java
Labels: enhancement

#317 :sparkles: [Feature] 토너먼트 관리자 삭제 API 추가
  src/main/java/com/gg/server/admin/tournament/controller/TournamentAdminController.java
  src/main/java/com/gg/server/admin/tournament/dto/TournamentAdminUpdateRequestDto.java
  src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java
  src/main/java/com/gg/server/domain/tournament/data/Tournament.java
  src/main/java/com/gg/server/domain/tournament/data/TournamentGame.java
  src/main/java/com/gg/server/domain/tournament/data/TournamentGameRepository.java
  src/main/java/com/gg/server/domain/tournament/data/TournamentRepository.java
  src/main/java/com/gg/server/global/exception/ErrorCode.java
  src/test/java/com/gg/server/admin/tournament/controller/TournamentAdminControllerTest.java
  src/test/java/com/gg/server/admin/tournament/service/TournamentAdminServiceTest.java
  src/test/java/com/gg/server/utils/TestDataUtils.java
Labels: enhancement

#331 ✨ [Feature] 토너먼트 전체 리스트 조회 Api 추가
  src/main/java/com/gg/server/domain/tournament/controller/TournamentController.java
  src/main/java/com/gg/server/domain/tournament/data/Tournament.java
  src/main/java/com/gg/server/domain/tournament/data/TournamentRepository.java
  src/main/java/com/gg/server/domain/tournament/data/TournamentUser.java
  src/main/java/com/gg/server/domain/tournament/data/TournamentUserRepository.java
  src/main/java/com/gg/server/domain/tournament/dto/TournamentFilterRequestDto.java
  src/main/java/com/gg/server/domain/tournament/dto/TournamentListResponseDto.java
  src/main/java/com/gg/server/domain/tournament/dto/TournamentResponseDto.java
  src/main/java/com/gg/server/domain/tournament/service/TournamentService.java
  src/main/java/com/gg/server/domain/tournament/type/TournamentStatus.java
  src/main/java/com/gg/server/domain/tournament/type/TournamentType.java
  src/main/java/com/gg/server/domain/tournament/validation/EnumValue.java
  src/main/java/com/gg/server/domain/tournament/validation/ValueOfEnumValidator.java
  src/main/java/com/gg/server/domain/user/dto/UserImageDto.java
  src/main/java/com/gg/server/global/exception/GlobalExceptionHandler.java
  src/test/java/com/gg/server/domain/tournament/controller/TournamentFindControllerTest.java
  src/test/java/com/gg/server/utils/TestDataUtils.java
Labels: enhancement

#336 :hammer: [Refactor] tournament에서 tournaments로 엔드포인트 수정
  src/main/java/com/gg/server/admin/tournament/controller/TournamentAdminController.java
  src/main/java/com/gg/server/domain/tournament/controller/TournamentController.java
  src/test/java/com/gg/server/admin/tournament/controller/TournamentAdminControllerTest.java
  src/test/java/com/gg/server/domain/tournament/controller/TournamentFindControllerTest.java
Labels: refactoring
