Repository 42organization/42gg.server.dev.v2, pull requests merged in 2024-03, with the labels that each got.

#666 [Feature] table 초기화 flyway 작성 및 방 전체 조회 api
  build.gradle
  gg-data/src/main/java/gg/data/party/Category.java
  gg-data/src/main/java/gg/data/party/Comment.java
  gg-data/src/main/java/gg/data/party/CommentReport.java
  gg-data/src/main/java/gg/data/party/GameTemplate.java
  gg-data/src/main/java/gg/data/party/Room.java
  gg-data/src/main/java/gg/data/party/RoomReport.java
  gg-data/src/main/java/gg/data/party/UserReport.java
  gg-data/src/main/java/gg/data/party/UserRoom.java
  gg-data/src/main/java/gg/data/party/type/RoomType.java
  gg-pingpong-api/src/main/java/gg/PingpongApiApplication.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/category/controller/CategoryAdminController.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/comment/controller/CommentAdminController.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/report/controller/ReportAdminController.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/room/controller/RoomAdminController.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/template/controller/TemplateAdminController.java
  gg-pingpong-api/src/main/java/gg/party/api/user/category/controller/CategoryController.java
  gg-pingpong-api/src/main/java/gg/party/api/user/comment/controller/CommentController.java
  gg-pingpong-api/src/main/java/gg/party/api/user/report/controller/ReportController.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/RoomController.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/RoomListResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/RoomResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomService.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/global/security/config/SecurityConfig.java
  gg-pingpong-api/src/main/resources/db/migration/V1.3__update_party_content.sql
  gg-pingpong-api/src/test/java/gg/ServerPingpongApiApplicationTests.java
  gg-repo/src/main/java/gg/repo/party/RoomRepository.java
Labels: enhancement

#668 [Feature] 참여한 방 조회 API
  gg-data/src/main/java/gg/data/party/UserRoom.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/RoomController.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomService.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/utils/GenerateRandomNickname.java
  gg-repo/src/main/java/gg/repo/party/UserRoomRepository.java
Labels: enhancement

#669 [Feature] 댓글 생성 api
  gg-data/src/main/java/gg/data/party/Comment.java
  gg-pingpong-api/src/main/java/gg/party/api/user/comment/controller/CommentController.java
  gg-pingpong-api/src/main/java/gg/party/api/user/comment/controller/request/CommentCreateReqDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/comment/service/CommentService.java
  gg-repo/src/main/java/gg/repo/party/CommentRepository.java
  gg-repo/src/main/java/gg/repo/party/UserRoomRepository.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
  gg-utils/src/main/java/gg/utils/exception/party/CommentNotValidException.java
  gg-utils/src/main/java/gg/utils/exception/party/RoomNotFoundException.java
  gg-utils/src/main/java/gg/utils/exception/party/RoomUpdateException.java
Labels: enhancement

#671 [Feature] 방 상세 조회 api
  gg-data/src/main/java/gg/data/party/Comment.java
  gg-data/src/main/java/gg/data/party/Room.java
  gg-data/src/main/java/gg/data/party/UserRoom.java
  gg-pingpong-api/src/main/java/gg/party/api/user/comment/service/CommentService.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/RoomController.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/request/RoomCreateReqDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/CommentResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/RoomDetailResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/RoomResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/UserRoomResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomService.java
  gg-pingpong-api/src/main/resources/db/migration/V1.3__update_party_content.sql
  gg-repo/src/main/java/gg/repo/party/CommentRepository.java
  gg-repo/src/main/java/gg/repo/party/UserRoomRepository.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
  gg-utils/src/main/java/gg/utils/exception/party/RoomNotFoundException.java
  gg-utils/src/main/java/gg/utils/exception/party/RoomReportedException.java
Labels: enhancement

#677 640 방 나가기 api
  gg-data/src/main/java/gg/data/party/Room.java
  gg-data/src/main/java/gg/data/party/UserRoom.java
  gg-data/src/main/java/gg/data/party/type/RoomType.java
  gg-pingpong-api/src/main/java/gg/party/api/user/comment/service/CommentService.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/RoomController.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/LeaveRoomResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomService.java
  gg-repo/src/main/java/gg/repo/party/RoomRepository.java
  gg-repo/src/main/java/gg/repo/party/UserRoomRepository.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
  gg-utils/src/main/java/gg/utils/exception/party/RoomNotFoundException.java
  gg-utils/src/main/java/gg/utils/exception/party/RoomNotOpenException.java
  gg-utils/src/main/java/gg/utils/exception/party/RoomNotParticipantException.java
  gg-utils/src/main/java/gg/utils/exception/party/UserNotFoundException.java
  gg-utils/src/testFixtures/java/gg/utils/TestDataUtils.java
Labels: enhancement

#686 ✨ [Feature] AdminRoom show변경 API
  gg-data/src/main/java/gg/data/party/Room.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/room/controller/RoomAdminController.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/room/controller/request/RoomShowChangeReqDto.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/room/service/RoomAdminService.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
  gg-utils/src/main/java/gg/utils/exception/party/RoomAlreadyHiddenException.java
  gg-utils/src/main/java/gg/utils/exception/party/RoomStatNotFoundException.java
Labels: enhancement

#685 [FEATURE] 댓글 숨김 ADMIN API
  gg-admin-repo/src/main/java/gg/admin/repo/comment/CommentAdminRepository.java
  gg-data/src/main/java/gg/data/party/Comment.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/comment/controller/CommentAdminController.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/comment/controller/request/CommentUpdateAdminRequestDto.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/comment/service/CommentAdminService.java
  gg-pingpong-api/src/main/java/gg/party/api/user/comment/controller/CommentController.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
  gg-utils/src/main/java/gg/utils/exception/party/CommentNotFoundException.java
Labels: enhancement

#687 [FIX] startRoom API without 복면가왕 logic
  gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/RoomController.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomService.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
  gg-utils/src/main/java/gg/utils/exception/party/CategoryNotFoundException.java
  gg-utils/src/main/java/gg/utils/exception/party/InvaildPeopleException.java
  gg-utils/src/main/java/gg/utils/exception/party/NotHostException.java
  gg-utils/src/main/java/gg/utils/exception/party/RoomNotEnoughPeopleException.java
Labels: enhancement

#689 [FEAT] #688 api module add
  build.gradle
  gg-pingpong-api/src/main/java/gg/PingpongApiApplication.java
  gg-pingpong-api/src/test/java/gg/pingpong/api/admin/coin/controller/CoinPolicyAdminControllerTest.java
  gg-recruit-api/build.gradle
  gg-recruit-api/src/main/java/gg/recruit/api/TestController.java
  gg-utils/build.gradle
  gg-utils/src/testFixtures/java/gg/utils/TestDataUtils.java
  settings.gradle
Labels: enhancement

#695 ✨ [Feature] 탬플릿 목록 조회 API
  gg-pingpong-api/src/main/java/gg/party/api/admin/template/controller/TemplateAdminController.java
  gg-pingpong-api/src/main/java/gg/party/api/user/templates/controller/TemplateController.java
  gg-pingpong-api/src/main/java/gg/party/api/user/templates/controller/response/TemplateResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/templates/service/TemplateService.java
  gg-repo/src/main/java/gg/repo/party/TemplateRepository.java
Labels: enhancement

#696 ✨ [Feature] 탬플릿 삭제 API
  gg-pingpong-api/src/main/java/gg/party/api/admin/templates/controller/TemplateAdminController.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/templates/service/TemplateAdminService.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
  gg-utils/src/main/java/gg/utils/exception/party/TemplateNotFoundException.java
Labels: enhancement

#683 💚 [chore] codecov, jacoco 모듈에 맞게 변경
  codecov.yml
  gg-utils/build.gradle
Labels: bug

#702 [FIX] #701 Fix/log path dev
  gg-pingpong-api/src/main/resources/logback-spring.xml
Labels: bug

#703 [FIX] #701 Fix/log path main
  gg-pingpong-api/src/main/resources/logback-spring.xml
Labels: bug

#706 [FEAT] add 방 신고 API without redis logic
  gg-data/src/main/java/gg/data/party/RoomReport.java
  gg-pingpong-api/src/main/java/gg/party/api/user/report/controller/ReportController.java
  gg-pingpong-api/src/main/java/gg/party/api/user/report/request/ReportRoomReqDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/report/service/ReportService.java
  gg-pingpong-api/src/main/java/gg/party/api/user/report/utils/PartyGivePenalty.java
  gg-repo/src/main/java/gg/repo/party/RoomReportRepository.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
  gg-utils/src/main/java/gg/utils/exception/party/AlredayReportedRoomException.java
Labels: enhancement

#697 [Feature] 카테고리 삭제 API 및 flyway v1.3 수정
  gg-admin-repo/src/main/java/gg/admin/repo/category/CategoryAdminRepository.java
  gg-admin-repo/src/main/java/gg/admin/repo/room/RoomAdminRepository.java
  gg-data/src/main/java/gg/data/party/PartyPenalty.java
  gg-data/src/main/java/gg/data/party/Room.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/category/controller/CategoryAdminController.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/category/service/CategoryAdminService.java
  gg-pingpong-api/src/main/resources/db/migration/V1.3__update_party_content.sql
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
  gg-utils/src/main/java/gg/utils/exception/party/DefaultCategoryNeedException.java
Labels: enhancement

#691 [FEAT] #558 my applications get
  .gitignore
  gg-data/src/main/java/gg/data/recruit/application/Application.java
  gg-data/src/main/java/gg/data/recruit/recruitment/Recruitments.java
  gg-recruit-api/build.gradle
  gg-recruit-api/src/main/java/gg/recruit/api/TestController.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/application/controller/ApplicationController.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/application/controller/response/ApplicationResDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/application/controller/response/MyApplicationsResDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/application/service/ApplicationService.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/application/service/response/ApplicationDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/application/service/response/ApplicationListDto.java
  gg-recruit-api/src/test/java/gg/recruit/api/TestSpringBootApplication.java
  gg-recruit-api/src/test/java/gg/recruit/api/user/application/controller/ApplicationControllerTest.java
  gg-recruit-api/src/test/resources/application.yml
  gg-repo/src/main/java/gg/repo/recruit/user/application/ApplicationRepository.java
  gg-repo/src/main/java/gg/repo/recruit/user/recruitment/RecruitmentRepository.java
  gg-utils/src/testFixtures/java/gg/utils/RecruitMockData.java
Labels: enhancement

#705 [Feature] 카테고리 추가 API
  gg-admin-repo/src/main/java/gg/admin/repo/category/CategoryAdminRepository.java
  gg-data/src/main/java/gg/data/party/Category.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/category/controller/CategoryAdminController.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/category/controller/request/CategoryAddAdminReqDto.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/category/service/CategoryAdminService.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
  gg-utils/src/main/java/gg/utils/exception/party/CategoryDuplicateException.java
Labels: enhancement

#700 ✨ [Feature] 탬플릿 추가 API
  gg-data/src/main/java/gg/data/party/GameTemplate.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/templates/controller/TemplateAdminController.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/templates/controller/request/TemplateAdminCreateReqDto.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/templates/service/TemplateAdminService.java
Labels: enhancement

#711 [FEAT] 댓글 신고 API with 패널티 부여 로직
  gg-data/src/main/java/gg/data/party/CommentReport.java
  gg-data/src/main/java/gg/data/party/PartyPenalty.java
  gg-data/src/main/java/gg/data/party/Room.java
  gg-pingpong-api/src/main/java/gg/party/api/user/report/controller/ReportController.java
  gg-pingpong-api/src/main/java/gg/party/api/user/report/request/ReportReqDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/report/service/ReportService.java
  gg-pingpong-api/src/main/java/gg/party/api/user/report/utils/PartyGivePenalty.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomService.java
  gg-repo/src/main/java/gg/repo/party/CommentReportRepository.java
  gg-repo/src/main/java/gg/repo/party/PartyPenaltyRepository.java
  gg-repo/src/main/java/gg/repo/party/UserRoomRepository.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
  gg-utils/src/main/java/gg/utils/exception/party/AlredayReportedException.java
  gg-utils/src/main/java/gg/utils/exception/party/AlredayReportedRoomException.java
  gg-utils/src/main/java/gg/utils/exception/party/SelfReportException.java
Labels: enhancement

#525 ✨ [Feature] 게임 매칭 큐 조회 API 개발
  gg-admin-repo/src/main/java/gg/admin/repo/manage/AdminSlotManagementsRepository.java
  gg-admin-repo/src/main/java/gg/admin/repo/match/RedisMatchTimeAdminRepository.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/admin/match/controller/MatchAdminController.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/admin/match/controller/response/EnrolledMatch.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/admin/match/controller/response/EnrolledMatchesResponseDto.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/admin/match/service/MatchAdminService.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/admin/match/service/dto/MatchUser.java
  gg-pingpong-api/src/test/java/gg/pingpong/api/admin/match/service/MatchAdminServiceTest.java
  gg-pingpong-api/src/test/java/gg/pingpong/api/admin/match/service/MatchAdminServiceUnitTest.java
  gg-repo/src/main/java/gg/repo/match/RedisMatchTimeRepository.java
Labels: enhancement

#715 ✨ [Feature] 탬플릿 수정 API
  gg-data/src/main/java/gg/data/party/GameTemplate.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/templates/controller/TemplateAdminController.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/templates/controller/request/TemplateAdminUpdateReqDto.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/templates/service/TemplateAdminService.java
Labels: enhancement

#725 [REFACT] #724 Jpa 설정 클래스 통합
  gg-pingpong-api/src/main/java/gg/pingpong/api/global/config/JpaAuditingConfig.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/global/config/JpaConfig.java
Labels: refactoring

#732 [FEAT] 패널티 추가, 수정 API 및 패널티 부여 로직 수정 및 RoomService에서 패널티 유저 체크 로직 추가
  gg-admin-repo/src/main/java/gg/admin/repo/penalty/PartyPenaltyAdminRepository.java
  gg-data/src/main/java/gg/data/party/PartyPenalty.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/penalty/controller/PartyPenaltyAdminController.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/penalty/request/PartyPenaltyAdminReqDto.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/penalty/service/PartyPenaltyAdminService.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/room/controller/RoomAdminController.java
  gg-pingpong-api/src/main/java/gg/party/api/user/report/controller/ReportController.java
  gg-pingpong-api/src/main/java/gg/party/api/user/report/controller/request/ReportReqDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/report/service/ReportService.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomService.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
  gg-utils/src/main/java/gg/utils/exception/party/OnPenaltyException.java
  gg-utils/src/main/java/gg/utils/exception/party/PartyPenaltyNotFoundException.java
  gg-utils/src/main/java/gg/utils/exception/party/PenaltyNotFoundException.java
Labels: enhancement

#737 [FEAT] #559 application detail get api
  gg-data/src/main/java/gg/data/recruit/application/ApplicationAnswer.java
  gg-data/src/main/java/gg/data/recruit/application/ApplicationAnswerCheckList.java
  gg-data/src/main/java/gg/data/recruit/application/ApplicationAnswerEntityDto.java
  gg-data/src/main/java/gg/data/recruit/application/ApplicationAnswerText.java
  gg-data/src/main/java/gg/data/recruit/application/CheckListEntityDto.java
  gg-data/src/main/java/gg/data/recruit/recruitment/CheckList.java
  gg-data/src/main/java/gg/data/recruit/recruitment/Question.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/global/config/SwaggerConfig.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/global/exception/GlobalExceptionHandler.java
  gg-pingpong-api/src/main/resources/db/migration/V2__recruit.sql
  gg-recruit-api/src/main/java/gg/recruit/api/user/controller/ApplicationController.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/controller/response/ApplicationResDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/controller/response/CheckListResDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/controller/response/FormResDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/controller/response/MyApplicationDetailResDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/controller/response/MyApplicationsResDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/service/ApplicationService.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/service/param/FindApplicationDetailParam.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/service/response/ApplicationListSvcDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/service/response/ApplicationSvcDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/service/response/ApplicationWithAnswerSvcDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/service/response/CheckListSvcDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/service/response/FormSvcDto.java
  gg-repo/src/main/java/gg/repo/recruit/user/application/ApplicationAnswerRepository.java
Labels: enhancement

#723 647 노쇼 신고 api
  gg-data/src/main/java/gg/data/party/UserReport.java
  gg-pingpong-api/src/main/java/gg/party/api/user/report/controller/ReportController.java
  gg-pingpong-api/src/main/java/gg/party/api/user/report/service/ReportService.java
  gg-repo/src/main/java/gg/repo/party/UserReportRepository.java
  gg-repo/src/main/java/gg/repo/party/UserRoomRepository.java
  gg-utils/src/main/java/gg/utils/exception/party/UserAlreadyInRoom.java
Labels: enhancement

#738 #552 feature 공고 상세 조회 api
  gg-data/src/main/java/gg/data/recruit/recruitment/Question.java
  gg-data/src/main/java/gg/data/recruit/recruitment/Recruitments.java
  gg-data/src/main/java/gg/data/recruit/recruitment/enums/InputType.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/controller/RecruitmentController.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/controller/response/CheckItemResDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/controller/response/FormDetailResDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/controller/response/RecruitmentDetailResDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/service/ApplicationService.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/service/QuestionService.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/service/RecruitmentService.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/service/response/CheckItemSvcDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/service/response/FormDetailSvcDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/service/response/RecruitmentDetailSvcDto.java
  gg-recruit-api/src/test/java/gg/recruit/api/user/controller/RecruitmentControllerTest.java
  gg-repo/src/main/java/gg/repo/recruit/user/application/ApplicationRepository.java
  gg-repo/src/main/java/gg/repo/recruit/user/recruitment/CheckListRepository.java
  gg-repo/src/main/java/gg/repo/recruit/user/recruitment/QuestionRepository.java
  gg-repo/src/main/java/gg/repo/recruit/user/recruitment/RecruitmentRepository.java
  gg-utils/src/main/java/gg/utils/exception/custom/NotExistException.java
  gg-utils/src/testFixtures/java/gg/utils/RecruitMockData.java
Labels: enhancement

#739 726 refactoring jpa 쿼리 최적화
  gg-admin-repo/src/main/java/gg/admin/repo/game/GameAdminRepository.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/admin/game/service/GameAdminService.java
Labels: enhancement

#744 ✨ [Feature] && [Refactoring] 테스트코드 작성 및 폴더 구조 변경
  gg-admin-repo/src/main/java/gg/admin/repo/penalty/PartyPenaltyAdminRepository.java
  gg-data/src/main/java/gg/data/party/Room.java
  gg-data/src/main/java/gg/data/party/UserRoom.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/penalty/request/PartyPenaltyAdminReqDto.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/penalty/service/PartyPenaltyAdminService.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/room/service/RoomAdminService.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/RoomController.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/request/RoomCreateReqDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/LeaveRoomResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/RoomDetailResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/RoomResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/UserRoomResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomFindService.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomManagementService.java
  gg-pingpong-api/src/test/java/gg/party/api/user/room/RoomControllerTest.java
  gg-repo/src/main/java/gg/repo/party/UserRoomRepository.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
  gg-utils/src/main/java/gg/utils/exception/party/RoomMinMaxPeople.java
  gg-utils/src/main/java/gg/utils/exception/party/RoomNotOpenException.java
  gg-utils/src/testFixtures/java/gg/utils/TestDataUtils.java
Labels: bug, enhancement, refactoring, test

#743 ✨ [Feature] 댓글 테스트 코드 추가
  gg-pingpong-api/src/main/java/gg/party/api/user/comment/controller/request/CommentCreateReqDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/comment/service/CommentService.java
  gg-pingpong-api/src/test/java/gg/party/api/user/comment/CommentControllerTest.java
Labels: enhancement

#742 #555 feature 지원하기 api
  gg-data/src/main/java/gg/data/recruit/application/ApplicationAnswer.java
  gg-data/src/main/java/gg/data/recruit/application/ApplicationAnswerCheckList.java
  gg-data/src/main/java/gg/data/recruit/application/ApplicationAnswerText.java
  gg-data/src/main/java/gg/data/recruit/recruitment/Question.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/controller/ApplicationController.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/controller/request/RecruitApplyFormListReqDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/controller/request/RecruitApplyFormReqDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/controller/response/ApplicationResultResDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/service/ApplicationService.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/service/param/RecruitApplyFormParam.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/service/param/RecruitApplyParam.java
  gg-recruit-api/src/test/java/gg/recruit/api/user/RecruitMockData.java
  gg-recruit-api/src/test/java/gg/recruit/api/user/controller/ApplicationControllerTest.java
  gg-recruit-api/src/test/java/gg/recruit/api/user/controller/RecruitmentControllerTest.java
  gg-repo/src/main/java/gg/repo/recruit/user/application/ApplicationRepository.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
  gg-utils/src/main/java/gg/utils/exception/custom/DuplicationException.java
Labels: enhancement, test

#746 [FEAT] #556 feature 지원 취소 api
  gg-data/src/main/java/gg/data/recruit/application/Application.java
  gg-data/src/main/java/gg/data/recruit/recruitment/Recruitments.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/controller/ApplicationController.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/service/ApplicationService.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/service/param/DelApplicationParam.java
  gg-recruit-api/src/test/java/gg/recruit/api/user/RecruitMockData.java
  gg-recruit-api/src/test/java/gg/recruit/api/user/controller/ApplicationControllerTest.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
  gg-utils/src/main/java/gg/utils/exception/custom/ForbiddenException.java
Labels: enhancement

#749 [FEAT] #557 patch application api
  gg-data/src/main/java/gg/data/recruit/application/ApplicationAnswer.java
  gg-data/src/main/java/gg/data/recruit/application/ApplicationAnswerCheckList.java
  gg-data/src/main/java/gg/data/recruit/application/ApplicationAnswerText.java
  gg-data/src/main/java/gg/data/recruit/recruitment/CheckList.java
  gg-data/src/main/java/gg/data/recruit/recruitment/Question.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/controller/ApplicationController.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/controller/request/CheckListFormRequest.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/controller/request/FormPatchRequestDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/controller/request/FormRequest.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/controller/request/TextFormRequest.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/service/ApplicationService.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/service/param/CheckListFormParam.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/service/param/FormParam.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/service/param/FormPatchParam.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/service/param/TextFormParam.java
  gg-recruit-api/src/test/java/gg/recruit/api/user/RecruitMockData.java
  gg-recruit-api/src/test/java/gg/recruit/api/user/controller/ApplicationControllerTest.java
  gg-repo/src/main/java/gg/repo/recruit/user/application/ApplicationAnswerRepository.java
  gg-repo/src/main/java/gg/repo/recruit/user/recruitment/CheckListRepository.java
Labels: enhancement

#462 :memo: [Docs] 5기 README.md 업데이트
  README.md
Labels: documentation

#756 🧪 [Test] Admin 템플릿 추가, 제거, 수정 테스트코드 작성
  gg-pingpong-api/src/main/java/gg/party/api/admin/templates/controller/TemplateAdminController.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/templates/controller/request/TemplateAdminCreateReqDto.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/templates/controller/request/TemplateAdminUpdateReqDto.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/templates/service/TemplateAdminService.java
  gg-pingpong-api/src/test/java/gg/party/api/admin/template/TemplateAdminControllerTest.java
  gg-utils/src/testFixtures/java/gg/utils/TestDataUtils.java
Labels: test

#758 🧪 [Test] Admin 댓글, 방, 노쇼 신고 리스트 조회 테스트 코드 작성
  gg-pingpong-api/src/main/java/gg/party/api/admin/report/controller/response/CommentReportAdminResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/report/controller/response/RoomReportAdminResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/report/controller/response/UserReportAdminResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/report/service/ReportAdminService.java
  gg-pingpong-api/src/test/java/gg/party/api/admin/report/ReportAdminControllerTest.java
  gg-utils/src/testFixtures/java/gg/utils/TestDataUtils.java
Labels: test

#762 🧪 [Test] Admin 방 목록 조회 및 방 상세 조회 및 방 Status변경 테스트코드 작성
  gg-pingpong-api/src/main/java/gg/party/api/admin/room/controller/request/RoomShowChangeReqDto.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/room/service/RoomAdminService.java
  gg-pingpong-api/src/test/java/gg/party/api/admin/room/RoomAdminControllerTest.java
  gg-utils/src/main/java/gg/utils/exception/party/RoomSameStatusException.java
  gg-utils/src/testFixtures/java/gg/utils/TestDataUtils.java
Labels: test

#768 🧪 [Test] && 🐛 [Bug] 방 시작하기 및 참여하기에서 시작되는 부분 테스트 코드 작성 && 마감된 방 && Finish방 Intra조회
  gg-pingpong-api/src/main/java/gg/party/api/admin/room/service/RoomStatusService.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomFindService.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomManagementService.java
  gg-pingpong-api/src/test/java/gg/party/api/user/room/RoomControllerTest.java
  gg-repo/src/main/java/gg/repo/party/RoomRepository.java
  gg-utils/src/main/java/gg/utils/exception/party/RoomNotEnoughPeopleException.java
  gg-utils/src/main/java/gg/utils/exception/party/RoomNotParticipantException.java
Labels: bug, refactoring, test

#754 [test] 카테고리, 템플릿 조회 테스트 코드 추가
  gg-pingpong-api/src/main/java/gg/party/api/user/category/controller/CategoryController.java
  gg-pingpong-api/src/main/java/gg/party/api/user/category/controller/response/CategoryResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/category/service/CategoryService.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/request/RoomCreateReqDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/RoomDetailResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/RoomResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomManagementService.java
  gg-pingpong-api/src/main/java/gg/party/api/user/template/controller/TemplateController.java
  gg-pingpong-api/src/main/java/gg/party/api/user/template/controller/response/TemplateListResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/template/controller/response/TemplateResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/template/service/TemplateService.java
  gg-pingpong-api/src/main/java/gg/party/api/user/templates/service/TemplateService.java
  gg-pingpong-api/src/test/java/gg/party/api/admin/template/TemplateAdminControllerTest.java
  gg-pingpong-api/src/test/java/gg/party/api/user/category/CategoryControllerTest.java
  gg-pingpong-api/src/test/java/gg/party/api/user/room/RoomControllerTest.java
  gg-pingpong-api/src/test/java/gg/party/api/user/template/TemplateControllerTest.java
  gg-repo/src/main/java/gg/repo/party/CategoryRepository.java
  gg-repo/src/main/java/gg/repo/party/PartyPenaltyRepository.java
  gg-utils/src/testFixtures/java/gg/utils/TestDataUtils.java
Labels: test

#767 🧪 [Test] 패널티 관련 테스트 코드 작성
  gg-pingpong-api/src/main/java/gg/party/api/admin/penalty/controller/PartyPenaltyAdminController.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/penalty/controller/request/PartyPenaltyAdminReqDto.java
  gg-pingpong-api/src/test/java/gg/party/api/admin/penalty/PartyPenaltyControllerTest.java
  gg-repo/src/main/java/gg/repo/party/PartyPenaltyRepository.java
Labels: test

#770 🔨 [Refactoring] && 🧪 [Test] Party 테스트코드 리팩토링 및 중복처리를 위한 에러코드 수정에 따른 test 코드 추가
  gg-pingpong-api/src/main/java/gg/party/api/admin/comment/service/CommentAdminService.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/room/service/RoomAdminService.java
  gg-pingpong-api/src/main/java/gg/party/api/user/comment/controller/request/CommentCreateReqDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/comment/service/CommentService.java
  gg-pingpong-api/src/test/java/gg/party/api/admin/category/CategoryAdminControllerTest.java
  gg-pingpong-api/src/test/java/gg/party/api/admin/comment/CommentAdminControllerTest.java
  gg-pingpong-api/src/test/java/gg/party/api/admin/report/ReportAdminControllerTest.java
  gg-pingpong-api/src/test/java/gg/party/api/admin/room/RoomAdminControllerTest.java
  gg-pingpong-api/src/test/java/gg/party/api/admin/template/TemplateAdminControllerTest.java
  gg-pingpong-api/src/test/java/gg/party/api/user/comment/CommentControllerTest.java
  gg-pingpong-api/src/test/java/gg/party/api/user/room/RoomControllerTest.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
  gg-utils/src/main/java/gg/utils/exception/party/ChangeSameStatusException.java
  gg-utils/src/main/java/gg/utils/exception/party/RoomSameStatusException.java
Labels: refactoring, test

#774 🐛 [Bug] 카테고리가 etc로 나오는 버그 && admin 템플릿 수정에서 최대인원 최소인원에 상관없이 저장되는 버그
  gg-pingpong-api/src/main/java/gg/party/api/admin/templates/controller/request/TemplateAdminCreateReqDto.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/templates/controller/request/TemplateAdminUpdateReqDto.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/templates/service/TemplateAdminService.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/request/RoomCreateReqDto.java
  gg-pingpong-api/src/test/java/gg/party/api/admin/category/CategoryAdminControllerTest.java
  gg-pingpong-api/src/test/java/gg/party/api/admin/template/TemplateAdminControllerTest.java
  gg-repo/src/main/java/gg/repo/party/CategoryRepository.java
  gg-utils/src/main/java/gg/utils/exception/party/DefaultCategoryNeedException.java
Labels: bug, test

#772 🔨 [Refactoring] Lazy fetch type 리펙토링
  gg-pingpong-api/src/main/java/gg/party/api/admin/penalty/service/PartyPenaltyAdminService.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/report/service/ReportAdminService.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/room/service/RoomAdminService.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomFindService.java
  gg-repo/src/main/java/gg/repo/party/CommentReportRepository.java
  gg-repo/src/main/java/gg/repo/party/CommentRepository.java
  gg-repo/src/main/java/gg/repo/party/PartyPenaltyRepository.java
  gg-repo/src/main/java/gg/repo/party/RoomReportRepository.java
  gg-repo/src/main/java/gg/repo/party/UserReportRepository.java
Labels: enhancement

#776 🐛 [Bug] 카테고리가 ID순이 아닌 이름순으로 정렬되는 버그 수정
  gg-pingpong-api/src/main/java/gg/party/api/admin/room/controller/response/AdminRoomDetailResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/room/controller/response/AdminRoomResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/templates/controller/request/TemplateAdminCreateReqDto.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/templates/controller/request/TemplateAdminUpdateReqDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/category/service/CategoryService.java
  gg-pingpong-api/src/main/java/gg/party/api/user/template/controller/response/TemplateResDto.java
Labels: bug

#779 🐛 [Bug] [Refactoring] 6기 Party 서비스 전체 리팩토링 중 찾은 버그들 수정
  gg-pingpong-api/src/main/java/gg/party/api/user/category/controller/response/CategoryListResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/CommentResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/LeaveRoomResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/RoomCreateResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/RoomDetailResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/RoomJoinResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/RoomListResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/RoomResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/RoomStartResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/UserRoomResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomFindService.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomManagementService.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/utils/GenerateRandomNickname.java
  gg-pingpong-api/src/main/java/gg/party/api/user/template/controller/TemplateController.java
  gg-pingpong-api/src/main/java/gg/party/api/user/template/controller/response/TemplateListResDto.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/user/noti/service/sns/SlackPartybotService.java
  gg-repo/src/main/java/gg/repo/party/RoomRepository.java
  gg-repo/src/main/java/gg/repo/party/UserRoomRepository.java
Labels: bug

#782 🔨 [Refactoring] 6기 Party 서비스 전체 리팩토링
  gg-data/src/main/java/gg/data/party/GameTemplate.java
  gg-data/src/main/java/gg/data/party/PartyPenalty.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/category/service/CategoryAdminService.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/penalty/service/PartyPenaltyAdminService.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/room/controller/RoomAdminController.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/room/service/RoomAdminService.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/templates/controller/request/TemplateAdminUpdateReqDto.java
  gg-pingpong-api/src/main/java/gg/party/api/admin/templates/service/TemplateAdminService.java
  gg-pingpong-api/src/main/java/gg/party/api/user/category/service/CategoryService.java
  gg-pingpong-api/src/main/java/gg/party/api/user/comment/service/CommentService.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomManagementService.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/user/noti/service/sns/SlackPartybotService.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/user/noti/service/sns/SlackbotService.java
Labels: bug, refactoring

#785 🐛 [Bug] party penalty 여러번 받은 유저는 영원히 사용할 수 없는 버그 수정 및 (패널티 수정) 버그 수정
  gg-pingpong-api/src/main/java/gg/party/api/admin/penalty/controller/request/PartyPenaltyAdminReqDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/category/service/CategoryService.java
  gg-pingpong-api/src/main/java/gg/party/api/user/comment/service/CommentService.java
  gg-pingpong-api/src/main/java/gg/party/api/user/report/service/ReportService.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomManagementService.java
  gg-repo/src/main/java/gg/repo/party/PartyPenaltyRepository.java
Labels: bug

#788 🐛 [Bug] 방 생성시 카테고리를 프론트에서 받지 못하는 버그
  gg-pingpong-api/src/main/java/gg/party/api/user/category/service/CategoryService.java
  gg-pingpong-api/src/main/java/gg/party/api/user/comment/service/CommentService.java
  gg-pingpong-api/src/main/java/gg/party/api/user/report/service/ReportService.java
  gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomManagementService.java
  gg-pingpong-api/src/test/java/gg/party/api/user/category/CategoryControllerTest.java
  gg-repo/src/main/java/gg/repo/party/PartyPenaltyRepository.java
Labels: bug

#781 [FEAT] recruit status change api
  .gitignore
  gg-data/src/main/java/gg/data/recruit/recruitment/Recruitments.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/global/config/SwaggerConfig.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/AdminRecruitmentController.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/request/UpdateStatusRequestDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/AdminRecruitmentService.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/UpdateRecruitStatusParam.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/controller/ApplicationController.java
  gg-recruit-api/src/test/java/gg/recruit/api/admin/controller/AdminRecruitmentControllerTest.java
  gg-recruit-api/src/test/java/gg/recruit/api/user/controller/ApplicationControllerTest.java
Labels: enhancement

#789 ✨ [Feature] 결과 message 등록 api
  build.gradle
  gg-admin-repo/src/main/java/gg/admin/repo/recruit/manage/RecruitResultMessageRepository.java
  gg-admin-repo/src/test/java/gg/admin/repo/TestSpringBootApplication.java
  gg-admin-repo/src/test/java/gg/admin/repo/recurit/maage/RecruitResultMessageRepositoryTest.java
  gg-admin-repo/src/test/resources/application.yml
  gg-data/src/main/java/gg/data/recruit/manage/ResultMessage.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/RecruitmentResultMessageAdminController.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/RecruitmentResultMessageAdminService.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/RecruitmentResultMessageAdminServiceImpl.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/dto/RecruitmentResultMessageDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/dto/RecruitmentResultMessageDtoMapper.java
  gg-recruit-api/src/test/java/gg/recruit/api/admin/controller/RecruitmentResultMessageAdminControllerUnitTest.java
  gg-recruit-api/src/test/java/gg/recruit/api/admin/integration/RecruitmentResultMessageIntegrationTest.java
  gg-recruit-api/src/test/java/gg/recruit/api/admin/service/RecruitmentResultMessageAdminServiceImplTest.java
Labels: enhancement

#797 ✨ [Feature] 공고 전체 조회 API
  gg-admin-repo/src/main/java/gg/admin/repo/recruit/RecruitmentAdminRepository.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/RecruitmentAdminController.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/response/CreatedRecruitmentResponse.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/response/RecruitmentDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/response/RecruitmentsResponse.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/RecruitmentAdminService.java
  gg-recruit-api/src/test/java/gg/recruit/api/RecruitMockData.java
  gg-recruit-api/src/test/java/gg/recruit/api/admin/RecruitAdminMockData.java
  gg-recruit-api/src/test/java/gg/recruit/api/admin/controller/AdminRecruitmentControllerTest.java
  gg-recruit-api/src/test/java/gg/recruit/api/admin/integration/RecruitmentAdminIntegrationTest.java
  gg-recruit-api/src/test/java/gg/recruit/api/admin/service/RecruitmentAdminServiceUnitTest.java
  gg-recruit-api/src/test/java/gg/recruit/api/user/controller/ApplicationControllerTest.java
  gg-recruit-api/src/test/java/gg/recruit/api/user/controller/RecruitmentControllerTest.java
Labels: enhancement

#796 ✨ [Feature] 결과 message 조회 api
  codecov.yml
  gg-admin-repo/src/main/java/gg/admin/repo/recruit/manage/RecruitResultMessageRepository.java
  gg-admin-repo/src/test/java/gg/admin/repo/recurit/maage/RecruitResultMessageRepositoryTest.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/RecruitmentResultMessageAdminController.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/response/GetRecruitmentResultMessageResponseDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/response/GetRecruitmentResultMessagesResponseDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/RecruitmentResultMessageAdminService.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/RecruitmentResultMessageAdminServiceImpl.java
  gg-recruit-api/src/test/java/gg/recruit/api/admin/controller/RecruitmentResultMessageAdminControllerUnitTest.java
Labels: enhancement

#791 🔨 [Refactoring + Feature] 패널티 확인 API 작성 및 패널티 정책 수정 #790
  gg-data/src/main/java/gg/data/party/type/RoomType.java
  gg-pingpong-api/logs/error.log
  gg-pingpong-api/src/main/java/gg/party/api/user/category/controller/CategoryController.java
  gg-pingpong-api/src/main/java/gg/party/api/user/category/service/CategoryService.java
  gg-pingpong-api/src/main/java/gg/party/api/user/penalty/controller/PartyPenaltyController.java
  gg-pingpong-api/src/main/java/gg/party/api/user/penalty/controller/response/PenaltyResDto.java
  gg-pingpong-api/src/main/java/gg/party/api/user/penalty/service/PartyPenaltyService.java
  gg-pingpong-api/src/main/java/gg/party/api/user/report/service/ReportService.java
  gg-pingpong-api/src/test/java/gg/party/api/user/category/CategoryControllerTest.java
  gg-pingpong-api/src/test/java/gg/party/api/user/penalty/PartyPenaltyControllerTest.java
  gg-utils/src/main/java/gg/utils/exception/party/AlreadyReportedException.java
Labels: bug, enhancement, refactoring
