Repository 42organization/42gg.server.dev.v2, pull requests merged in 2024-04, with the labels that each got.

#799 ✨ [Feature] 최종결과 등록
  build.gradle
  gg-admin-repo/src/main/java/gg/admin/repo/recruit/ApplicationAdminRepository.java
  gg-admin-repo/src/test/java/gg/admin/repo/recruit/ApplicationAdminRepositoryTest.java
  gg-data/src/main/java/gg/data/recruit/application/Application.java
  gg-data/src/main/java/gg/data/recruit/application/enums/ApplicationStatus.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/RecruitmentAdminController.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/request/SetFinalApplicationStatusResultReqDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/RecruitmentAdminService.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/dto/UpdateApplicationStatusDto.java
  gg-recruit-api/src/test/java/gg/recruit/api/WebMvcTestApplicationContext.java
  gg-recruit-api/src/test/java/gg/recruit/api/admin/controller/RecruitmentAdminControllerUnitTest.java
  gg-recruit-api/src/test/java/gg/recruit/api/admin/controller/RecruitmentResultMessageAdminControllerUnitTest.java
  gg-recruit-api/src/test/java/gg/recruit/api/admin/service/RecruitmentAdminServiceTest.java
  gg-recruit-api/src/test/resources/application.yml
  gg-utils/src/testFixtures/java/gg/utils/TestDataUtils.java
Labels: enhancement

#800 ✨ [Feature] 공고 삭제 API
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/RecruitmentAdminController.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/RecruitmentAdminService.java
  gg-recruit-api/src/test/java/gg/recruit/api/admin/integration/RecruitmentAdminIntegrationTest.java
  gg-recruit-api/src/test/java/gg/recruit/api/admin/service/RecruitmentAdminServiceUnitTest.java
Labels: enhancement

#661 🧪 [Unit Test] usertextcolorcheckservice 테스트 코드
  gg-pingpong-api/src/main/java/gg/pingpong/api/user/user/service/UserTextColorCheckService.java
  gg-pingpong-api/src/test/java/gg/pingpong/api/user/user/service/UserTextColorCheckServiceUnitTest.java
Labels: documentation, refactoring, test

#735 🧪 [Unit Test] CoinPolicyAdminService 단위 테스트 코드
  gg-pingpong-api/src/main/java/gg/pingpong/api/admin/store/controller/response/CoinPolicyAdminResponseDto.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/admin/store/service/CoinAdminService.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/admin/store/service/CoinPolicyAdminService.java
  gg-pingpong-api/src/test/java/gg/pingpong/api/admin/store/controller/CoinAdminControllerTest.java
  gg-pingpong-api/src/test/java/gg/pingpong/api/admin/store/controller/CoinPolicyAdminControllerFailTest.java
  gg-pingpong-api/src/test/java/gg/pingpong/api/admin/store/controller/CoinPolicyAdminControllerTest.java
  gg-pingpong-api/src/test/java/gg/pingpong/api/admin/store/service/CoinAdminServiceUnitTest.java
  gg-pingpong-api/src/test/java/gg/pingpong/api/admin/store/service/CoinPolicyAdminServiceUnitTest.java
Labels: test

#628 🧪 [Unit Test] Game unit test
  gg-pingpong-api/src/main/java/gg/pingpong/api/user/game/service/GameFindService.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/user/game/service/GameService.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/user/game/service/GameStatusService.java
  gg-pingpong-api/src/test/java/gg/pingpong/api/user/game/service/GameFindServiceUnitTest.java
  gg-pingpong-api/src/test/java/gg/pingpong/api/user/game/service/GameServiceUnitTest.java
  gg-pingpong-api/src/test/java/gg/pingpong/api/user/game/service/GameStatusServiceUnitTest.java
  gg-pingpong-api/src/test/java/gg/pingpong/api/user/game/service/PChangeServiceUnitTest.java
Labels: test

#807 [FIX] #806 auth 필요없는 객체 삭제, db검증로직 추가
  gg-pingpong-api/src/main/java/gg/pingpong/api/global/security/config/SecurityConfig.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/global/security/jwt/utils/TokenAuthenticationFilter.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/global/security/service/CustomUserDetailsService.java
Labels: enhancement

#805 ✨ [Feature] 서류 결과 등록 API
  .gitignore
  gg-admin-repo/src/main/java/gg/admin/repo/recruit/recruitment/RecruitStatusAdminRepository.java
  gg-admin-repo/src/test/java/gg/admin/repo/recruit/recruitment/RecruitStatusAdminRepositoryTest.java
  gg-data/src/main/java/gg/data/recruit/application/RecruitStatus.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/RecruitmentAdminController.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/request/InterviewRequestDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/RecruitmentAdminService.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/dto/UpdateApplicationStatusDto.java
  gg-recruit-api/src/test/java/gg/recruit/api/admin/integration/RecruitmentAdminIntegrationTest.java
  gg-recruit-api/src/test/java/gg/recruit/api/admin/service/RecruitmentAdminServiceTest.java
  gg-recruit-api/src/test/java/gg/recruit/api/admin/service/RecruitmentAdminServiceUnitTest.java
  gg-utils/src/testFixtures/java/gg/utils/TestDataUtils.java
Labels: enhancement

#798 ✨ [Feature] 알림 메세지 미리보기 API
  .gitignore
  gg-admin-repo/src/main/java/gg/admin/repo/recruit/manage/RecruitResultMessageRepository.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/RecruitmentResultMessageAdminController.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/request/GetRecruitmentResultMessagePreviewReqDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/response/GetRecruitmentResultMessagePreviewResDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/RecruitmentResultMessageAdminService.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/RecruitmentResultMessageAdminServiceImpl.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/dto/RecruitmentResultMessagePreviewResultSvcDto.java
  gg-recruit-api/src/test/java/gg/recruit/api/admin/integration/RecruitmentResultMessageIntegrationTest.java
Labels: enhancement

#801 ✨ [Feature] 지원자 결과 목록 조회 api
  gg-admin-repo/src/main/java/gg/admin/repo/recruit/ApplicationAdminRepository.java
  gg-admin-repo/src/test/java/gg/admin/repo/recruit/ApplicationAdminRepositoryTest.java
  gg-data/src/main/java/gg/data/recruit/application/Application.java
  gg-data/src/main/java/gg/data/recruit/application/RecruitStatus.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/RecruitmentAdminController.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/response/RecruitmentApplicantResultResponseDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/response/RecruitmentApplicantResultsResponseDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/RecruitmentAdminService.java
  gg-recruit-api/src/test/java/gg/recruit/api/admin/controller/RecruitmentAdminControllerUnitTest.java
  gg-utils/src/testFixtures/java/gg/utils/TestDataUtils.java
Labels: enhancement

#804 ✨ [Feature] 지원자 목록 확인 API
  gg-admin-repo/src/main/java/gg/admin/repo/recruit/ApplicationAdminRepository.java
  gg-admin-repo/src/test/java/gg/admin/repo/recruit/ApplicationAdminRepositoryTest.java
  gg-data/src/main/java/gg/data/recruit/application/Application.java
  gg-data/src/main/java/gg/data/recruit/application/ApplicationAnswer.java
  gg-data/src/main/java/gg/data/recruit/application/ApplicationAnswerCheckList.java
  gg-data/src/main/java/gg/data/recruit/application/ApplicationAnswerText.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/RecruitmentAdminController.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/response/GetRecruitmentApplicationDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/response/GetRecruitmentApplicationResponseDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/RecruitmentAdminService.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/dto/GetRecruitmentApplicationsDto.java
  gg-recruit-api/src/test/java/gg/recruit/api/admin/controller/RecruitmentAdminControllerUnitTest.java
  gg-recruit-api/src/test/java/gg/recruit/api/admin/controller/response/GetRecruitmentApplicationDtoTest.java
  gg-recruit-api/src/test/java/gg/recruit/api/admin/service/RecruitmentAdminServiceTest.java
  gg-utils/src/testFixtures/java/gg/utils/TestDataUtils.java
Labels: enhancement

#802 ✨ [Feature] 공고 수정 API
  .gitignore
  gg-admin-repo/src/main/java/gg/admin/repo/recruit/recruitment/QuestionAdminRepository.java
  gg-data/src/main/java/gg/data/recruit/recruitment/Question.java
  gg-data/src/main/java/gg/data/recruit/recruitment/Recruitment.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/RecruitmentAdminController.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/RecruitmentResultMessageAdminController.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/request/RecruitmentRequestDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/RecruitmentAdminService.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/RecruitmentResultMessageAdminService.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/RecruitmentResultMessageAdminServiceImpl.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/dto/RecruitmentResultMessagePreviewResultSvcDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/param/CheckListContent.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/param/FormParam.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/param/GetRecruitmentApplicationsParam.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/param/RecruitmentResultMessageDtoMapper.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/param/RecruitmentResultMessageParam.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/param/UpdateApplicationStatusParam.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/param/UpdateRecruitStatusParam.java
  gg-recruit-api/src/test/java/gg/recruit/api/RecruitMockData.java
  gg-recruit-api/src/test/java/gg/recruit/api/admin/controller/RecruitmentAdminControllerTest.java
  gg-recruit-api/src/test/java/gg/recruit/api/admin/controller/RecruitmentResultMessageAdminControllerUnitTest.java
  gg-recruit-api/src/test/java/gg/recruit/api/admin/integration/RecruitmentAdminIntegrationTest.java
  gg-recruit-api/src/test/java/gg/recruit/api/admin/integration/RecruitmentResultMessageIntegrationTest.java
  gg-recruit-api/src/test/java/gg/recruit/api/admin/service/RecruitmentAdminServiceTest.java
  gg-recruit-api/src/test/java/gg/recruit/api/admin/service/RecruitmentAdminServiceUnitTest.java
  gg-recruit-api/src/test/java/gg/recruit/api/admin/service/RecruitmentResultMessageAdminServiceImplTest.java
Labels: enhancement

#809 🐛 [Fix] 공고 admin API dto 수정 및 validation 추가
  gg-admin-repo/src/main/java/gg/admin/repo/recruit/RecruitmentAdminRepository.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/global/exception/GlobalExceptionHandler.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/RecruitmentAdminController.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/request/InterviewRequestDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/response/RecruitmentsResponse.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/RecruitmentAdminService.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/param/FormParam.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/result/AllRecruitmentsResult.java
  gg-recruit-api/src/test/java/gg/recruit/api/admin/service/RecruitmentAdminServiceUnitTest.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
Labels: bug, enhancement

#812 [FEAT] #811 admin recruit detail api
  gg-admin-repo/src/main/java/gg/admin/repo/recruit/RecruitmentAdminRepository.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/RecruitmentAdminController.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/response/CheckItemAdminResDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/response/FormDetailAdminResDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/response/RecruitmentAdminDetailResDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/RecruitmentAdminService.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/result/CheckItemAdminSvcDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/result/FormDetailAdminSvcDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/result/RecruitmentDetailAdminSvcDto.java
  gg-recruit-api/src/test/java/gg/recruit/api/admin/integration/RecruitmentAdminIntegrationTest.java
Labels: enhancement

#816 [FIX] #815 api response format
  gg-recruit-api/src/main/java/gg/recruit/api/user/controller/response/FormResDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/controller/response/MyApplicationDetailResDto.java
Labels: enhancement

#817 🐛 [Fix] 공고 전체 조회 API의 잘못된 응답 수정
  gg-admin-repo/src/main/java/gg/admin/repo/recruit/RecruitmentAdminRepository.java
  gg-data/src/main/java/gg/data/recruit/recruitment/Recruitment.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/RecruitmentAdminController.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/response/RecruitmentDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/response/RecruitmentsResponse.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/RecruitmentAdminService.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/controller/RecruitmentController.java
  gg-recruit-api/src/test/java/gg/recruit/api/admin/service/RecruitmentAdminServiceUnitTest.java
Labels: bug

#820 [FIX] api req, resp data format
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/RecruitmentAdminController.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/request/RecruitmentRequestDto.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/RecruitmentAdminService.java
  gg-recruit-api/src/main/java/gg/recruit/api/admin/service/param/CheckListContent.java
  gg-recruit-api/src/main/java/gg/recruit/api/user/controller/response/MyApplicationDetailResDto.java
Labels: enhancement

#822 🐛 [Bug] 방 나간 이후 참여한 방 목록에서 보이는 버그 #821
  gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomFindService.java
  gg-repo/src/main/java/gg/repo/party/UserRoomRepository.java
Labels: bug
