Repository 42organization/42gg.server.dev.v2, pull requests merged in 2024-01, with the labels that each got.

#467 [FIX] #232 admin 게임 관리 페이지에서 점수 수정 시 승패 수정 안되는 문제
  src/main/java/com/gg/server/admin/game/service/GameAdminService.java
  src/main/java/com/gg/server/domain/rank/redis/RankRedisService.java
  src/test/java/com/gg/server/admin/game/controller/GameAdminControllerTest.java
Labels: bug

#477 💚 [Setting] .gitattributes로 crlf 처리
  .gitattributes
Labels: enhancement

#482 🐛 [Fix] GUEST 토너먼트 참가 불가능하도록 수정
  src/main/java/com/gg/server/admin/tournament/dto/TournamentAdminCreateRequestDto.java
  src/main/java/com/gg/server/admin/tournament/dto/TournamentAdminUpdateRequestDto.java
  src/main/java/com/gg/server/global/security/config/SecurityConfig.java
  src/main/resources/db/migration/V3.1__update_tournament_content_column.sql
  src/test/java/com/gg/server/admin/tournament/controller/TournamentAdminControllerTest.java
Labels: bug, enhancement

#486 ✨ [Feature] 토너먼트 첫 라운드 경기 랜덤 매칭 기능 추가
  src/main/java/com/gg/server/domain/match/service/MatchTournamentService.java
Labels: enhancement

#491 :bug: [Fix] tournament contents에 대한 길이 valid 수정
  src/main/java/com/gg/server/admin/tournament/dto/TournamentAdminCreateRequestDto.java
  src/main/java/com/gg/server/admin/tournament/dto/TournamentAdminUpdateRequestDto.java
  src/main/java/com/gg/server/domain/tournament/data/Tournament.java
Labels: bug

#492 :bug: [Fix] tournament contents에 대한 길이 valid 수정
  src/main/java/com/gg/server/admin/tournament/dto/TournamentAdminCreateRequestDto.java
  src/main/java/com/gg/server/admin/tournament/dto/TournamentAdminUpdateRequestDto.java
  src/main/java/com/gg/server/domain/tournament/data/Tournament.java
Labels: bug

#479 [FIX] #478 path variable add
  src/main/java/com/gg/server/domain/rank/controller/RankV2Controller.java
Labels: bug

#494 [Fix] rank pagig bug 해결
  src/main/java/com/gg/server/domain/rank/data/RankRepository.java
  src/main/java/com/gg/server/domain/rank/service/RankService.java
  src/main/java/com/gg/server/domain/user/data/UserRepository.java
Labels: bug

#503 :bug: [Fix] 토너먼트 전체 조회 테스트 에러 수정
  src/test/java/com/gg/server/domain/tournament/controller/TournamentFindControllerTest.java
Labels: bug

#502 [Merge] merge dev into main
  src/main/java/com/gg/server/domain/tournament/controller/TournamentController.java
  src/test/java/com/gg/server/domain/tournament/controller/TournamentFindControllerTest.java
Labels: bug

#498 [Fix] 392 bug main flyway와 test schemasql 불일치
  src/main/resources/db/migration/V1.1__migration_42gg_5th.sql
  src/main/resources/db/migration/V1.1__migration_42gg_v2.sql
  src/main/resources/db/migration/V1.2__team_and_teamuser_cascade.sql
  src/main/resources/db/migration/V1.2__update_tournament_content_column.sql
  src/main/resources/db/migration/V1.3__add_prevent_delete_season_trigger.sql
  src/main/resources/db/migration/V1.4__pchange_add_is_checked_column.sql
  src/main/resources/db/migration/V1.5__insert_pchange_normal_ppp_result.sql
  src/main/resources/db/migration/V1__init.sql
  src/main/resources/db/migration/V2.1__add_item_creator.sql
  src/main/resources/db/migration/V2.2__add_item_type.sql
  src/main/resources/db/migration/V2.3__add_megaphone_receiptId.sql
  src/main/resources/db/migration/V2.4__modify_item_content_columns.sql
  src/main/resources/db/migration/V2.5__add_userImage_and_user_image_uri.sql
  src/main/resources/db/migration/V2__migration_42gg_4th.sql
  src/test/java/com/gg/server/utils/annotation/IntegrationTest.java
  src/test/java/com/gg/server/utils/annotation/IntegrationTestWithRedisTransaction.java
  src/test/java/com/gg/server/utils/annotation/TestTypeConstant.java
  src/test/java/com/gg/server/utils/annotation/UnitTest.java
  src/test/java/com/gg/server/utils/config/MySQLInitializer.java
  src/test/resources/application.yml
  src/test/resources/schema.sql
Labels: bug

#488 :hammer: [Refactor] 토너먼트 진행 시간동안의 슬롯 블락 로직 삭제
  src/main/java/com/gg/server/domain/match/service/MatchFindService.java
  src/main/java/com/gg/server/domain/match/utils/SlotGenerator.java
Labels: enhancement

#510 🐛 [Fix] codecov version to v3
  .github/workflows/test-code-validation.yml
Labels: bug

#513 ✨[Feature] slice test용 애너테이션 추가
  src/test/java/com/gg/server/utils/annotation/DataJpaUnitTest.java
  src/test/java/com/gg/server/utils/annotation/WebMvcUnitTest.java
Labels: enhancement, test

#473 [FIX] #232 admin 게임 관리 페이지에서 점수 수정 시 승패 수정 안되는 문제
  src/main/java/com/gg/server/admin/game/controller/GameAdminController.java
  src/main/java/com/gg/server/admin/game/data/GameAdminRepository.java
  src/main/java/com/gg/server/admin/game/service/GameAdminService.java
  src/main/java/com/gg/server/admin/team/data/TeamUserAdminRepository.java
  src/main/java/com/gg/server/domain/game/data/Game.java
  src/main/java/com/gg/server/domain/rank/data/Rank.java
  src/main/java/com/gg/server/domain/rank/redis/RankRedisService.java
  src/main/java/com/gg/server/domain/season/data/SeasonRepository.java
  src/main/java/com/gg/server/domain/season/exception/SeasonNotFoundException.java
  src/main/java/com/gg/server/domain/season/service/SeasonService.java
  src/main/java/com/gg/server/domain/team/data/Team.java
  src/main/java/com/gg/server/domain/user/data/User.java
  src/test/java/com/gg/server/admin/game/controller/GameAdminControllerTest.java
  src/test/resources/application.yml
Labels: bug

#518 🧪 [Test] MatchFindService 단위 테스트
  src/main/java/com/gg/server/domain/match/service/MatchFindService.java
  src/test/java/com/gg/server/domain/match/service/MatchFindServiceUnitTest.java
  src/test/java/com/gg/server/domain/match/service/MatchTournamentServiceTest.java
Labels: test
