Repository 42organization/42gg.server.dev.v2, pull requests merged in 2024-08, with the labels that each got.

#927 🔨 [Refactoring] Agenda Admin URL 변경 #926
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/controller/AgendaAdminController.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendaannouncement/controller/AgendaAnnouncementAdminController.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/controller/AgendaTeamAdminController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/AgendaTeamController.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agenda/controller/AgendaAdminControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agendaannouncement/controller/AgendaAnnouncementAdminControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agendateam/controller/AgendaTeamAdminControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendateam/AgendaTeamControllerTest.java
Labels: bug

#928 🔨 [Refactoring] Agenda 리펙토링 #925
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/AgendaController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/request/AgendaAwardsReqDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/request/AgendaCreateReqDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/request/validator/AgendaCapacityValid.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/request/validator/AgendaCapacityValidator.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/request/validator/AgendaScheduleValid.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/request/validator/AgendaScheduleValidator.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/response/AgendaSimpleResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/service/AgendaService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaannouncement/service/AgendaAnnouncementService.java
  gg-agenda-api/src/test/java/gg/agenda/api/AgendaMockData.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/controller/AgendaControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/controller/dto/AgendaCreateReqDtoTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/service/AgendaServiceTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendaannouncement/service/AgendaAnnouncementServiceTest.java
  gg-data/src/main/java/gg/data/agenda/Agenda.java
  gg-data/src/main/java/gg/data/agenda/AgendaTeamProfile.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaRepository.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaTeamProfileRepository.java
Labels: bug, refactoring

#931 🐛 [Bug] Team Create API 쿼리 잘못 쓴 부분 수정 및 Open Team Coaliton 추가 #930
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/response/OpenTeamResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaTeamProfileRepository.java
Labels: bug

#935 🐛 [Bug] AgendaCreateReqDto Custom Validtor 예외처리 로직 추가 #934
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/request/AgendaCreateReqDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/request/validator/AgendaScheduleValidator.java
Labels: bug

#937 🐛 [Bug] AgendaCreateReqDto DateTImeFormat 수정 #936
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/request/AgendaCreateReqDto.java
Labels: bug

#932 ✨ [Feature] 내가 참여 했던 대회 보기 API #855
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/AgendaProfileController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/response/AttendedAgendaListResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/AgendaProfileFindService.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendaprofile/AgendaProfileControllerTest.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaTeamProfileRepository.java
Labels: enhancement

#933 🐛 [Bug][Refactoring] 명세와 다른 부분 수정 및 GetMapping에서 Body받는 부분 수정 #930
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/AgendaController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/service/AgendaService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaannouncement/controller/AgendaAnnouncementController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/AgendaTeamController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/controller/TicketController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/service/TicketService.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/controller/AgendaControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/service/AgendaServiceTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendaannouncement/controller/AgendaAnnouncementControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendateam/AgendaTeamControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/ticket/TicketControllerTest.java
  gg-data/src/main/java/gg/data/agenda/Agenda.java
  gg-data/src/main/java/gg/data/agenda/Ticket.java
  gg-repo/src/main/java/gg/repo/agenda/TicketRepository.java
Labels: bug

#938 ✨ [Feature] Agenda 이미지 업로드 기능 추가 #929
  build.gradle
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/controller/AgendaAdminController.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/controller/request/AgendaAdminUpdateReqDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/service/AgendaAdminService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/AgendaController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/request/AgendaCreateReqDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/service/AgendaService.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agenda/controller/AgendaAdminControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agenda/service/AgendaAdminServiceTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agendateam/controller/AgendaTeamAdminControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/controller/AgendaControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/controller/dto/AgendaCreateReqDtoTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/service/AgendaServiceTest.java
  gg-data/src/main/java/gg/data/agenda/Agenda.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/global/security/service/CustomOAuth2UserService.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/global/utils/aws/AsyncNewItemImageUploader.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/global/utils/aws/AsyncNewUserImageUploader.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/global/utils/aws/ItemImageHandler.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/global/utils/aws/UserImageHandler.java
  gg-pingpong-api/src/test/java/gg/pingpong/api/admin/item/controller/ItemAdminControllerTest.java
  gg-pingpong-api/src/test/java/gg/pingpong/api/user/user/controller/UserControllerTest.java
  gg-utils/build.gradle
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
  gg-utils/src/main/java/gg/utils/file/FileDownloader.java
  gg-utils/src/main/java/gg/utils/file/ImageResizingUtil.java
  gg-utils/src/main/java/gg/utils/file/JpegMultipartFile.java
  gg-utils/src/main/java/gg/utils/file/handler/AwsImageHandler.java
  gg-utils/src/main/java/gg/utils/file/handler/ImageHandler.java
  gg-utils/src/testFixtures/java/gg/utils/converter/MultiValueMapConverter.java
  gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaFixture.java
  gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaTeamFixture.java
Labels: enhancement, refactoring

#943 ✨ [Feature] Agenda 취소하기 API 기능 구현 #939
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/service/AgendaTeamAdminService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/AgendaController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/service/AgendaService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/AgendaTeamController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/controller/AgendaControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/service/AgendaServiceTest.java
  gg-data/src/main/java/gg/data/agenda/Agenda.java
  gg-data/src/main/java/gg/data/agenda/AgendaTeam.java
  gg-data/src/main/java/gg/data/agenda/AgendaTeamProfile.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/global/exception/GlobalExceptionHandler.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaTeamRepository.java
  gg-utils/src/testFixtures/java/gg/utils/AgendaTestDataUtils.java
  gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaFixture.java
  gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaTeamFixture.java
  gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaTeamProfileFixture.java
Labels: enhancement, refactoring

#949 🔨 [Refactoring] Agenda Admin 조회 Query Parameter 변경 #948
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/controller/AgendaAdminController.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendaannouncement/controller/AgendaAnnouncementAdminController.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/controller/AgendaTeamAdminController.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/controller/request/AgendaTeamKeyReqDto.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agenda/controller/AgendaAdminControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agendaannouncement/controller/AgendaAnnouncementAdminControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agendateam/controller/AgendaTeamAdminControllerTest.java
Labels: enhancement, refactoring

#942 ✨ [Feature] 티켓 발급 완료 API #909
  gg-admin-repo/src/test/resources/application.yml
  gg-agenda-api/build.gradle
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/AgendaProfileService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/AgendaTeamController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/request/TeamUpdateReqDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/controller/TicketController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/service/TicketService.java
  gg-agenda-api/src/test/java/gg/agenda/api/AgendaMockData.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendateam/AgendaTeamControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/ticket/TicketControllerTest.java
  gg-agenda-api/src/test/resources/application.yml
  gg-auth/build.gradle
  gg-auth/src/main/java/gg/auth/FortyTwoAuthUtil.java
  gg-auth/src/main/java/gg/auth/utils/RefreshTokenUtil.java
  gg-data/src/main/java/gg/data/agenda/AgendaProfile.java
  gg-data/src/main/java/gg/data/agenda/Auth42Token.java
  gg-data/src/main/java/gg/data/agenda/Ticket.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/global/jwt/utils/TokenAuthenticationFilter.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/global/jwt/utils/TokenHeaders.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/global/security/config/SecurityConfig.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/global/security/handler/OAuthAuthenticationSuccessHandler.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/global/security/handler/OauthAuthenticationFailureHandler.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/global/security/repository/OAuthAuthorizationRequestBasedOnCookieRepository.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/global/security/service/CustomOAuth2UserService.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/user/noti/service/sns/SlackPartybotService.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/user/noti/service/sns/SlackbotService.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/user/user/controller/UserController.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/user/user/service/UserAuthenticationService.java
  gg-pingpong-api/src/main/resources/db/migration/V3__agenda.sql
  gg-pingpong-api/src/test/java/gg/pingpong/api/user/rank/controller/RankV2ControllerTest.java
  gg-pingpong-api/src/test/java/gg/pingpong/api/user/tournament/controller/TournamentControllerMvcTest.java
  gg-pingpong-api/src/test/java/gg/pingpong/api/user/user/service/UserAuthenticationServiceUnitTest.java
  gg-pingpong-api/src/test/resources/application.yml
  gg-recruit-api/src/test/resources/application.yml
  gg-repo/src/main/java/gg/repo/user/Auth42TokenRedisRepository.java
  gg-repo/src/main/java/gg/repo/user/JwtRedisRepository.java
  gg-utils/build.gradle
  gg-utils/src/main/java/gg/utils/ApplicationYmlRead.java
  gg-utils/src/main/java/gg/utils/DateTimeUtil.java
  gg-utils/src/main/java/gg/utils/cookie/CookieUtil.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
  gg-utils/src/main/java/gg/utils/external/ApiUtil.java
  gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaProfileFixture.java
  gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/TicketFixture.java
Labels: enhancement, test

#955 🐛 [Bug] Agenda 조회 API 응답 필드 추가 #951
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/controller/response/AgendaAdminResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/controller/response/AgendaTeamResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/response/AgendaResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/response/AgendaSimpleResDto.java
Labels: bug

#956 ✨ [Feature] Agenda Admin 목록 조회 기능 구현 #954
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/controller/AgendaAdminController.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/controller/response/AgendaAdminSimpleResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/service/AgendaAdminService.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agenda/controller/AgendaAdminControllerTest.java
Labels: enhancement

#958 [Bug] Value yml참조가 아닌 String으로 수정
  gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/service/TicketService.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/global/security/service/CustomOAuth2UserService.java
Labels: bug

#959 ✨ [Feature] Admin 티켓 생성 API #944
  gg-admin-repo/src/main/java/gg/admin/repo/agenda/AgendaAdminRepository.java
  gg-admin-repo/src/main/java/gg/admin/repo/agenda/TicketAdminRepository.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/ticket/controller/TicketAdminController.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/ticket/controller/request/TicketAddAdminReqDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/ticket/controller/response/TicketAddAdminResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/ticket/service/TicketAdminService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/response/CurrentAttendAgendaListResDto.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agendaprofile/AgendaProfileAdminControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/ticket/TicketAdminControllerTest.java
  gg-data/src/main/java/gg/data/agenda/Ticket.java
Labels: enhancement

#963 🐛 [Bug] Slack 및 Mail 모듈 URL 수정 #961
  gg-utils/src/main/java/gg/utils/sns/slack/SlackbotApiUtils.java
Labels: bug

#964 🐛 [Bug] Agenda Admin 전체조회 필드 추가 #962
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/controller/response/AgendaAdminResDto.java
Labels: enhancement

#965 ✨ [Feature] Confirm된 Team DeadLine 전까지 취소 가능하게 수정 #960
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/AgendaTeamController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/response/TeamDetailsResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendateam/AgendaTeamControllerTest.java
  gg-data/src/main/java/gg/data/agenda/AgendaTeam.java
Labels: enhancement

#966 🔨 [Refactoring] Pagenation 응답 totalSize 추가 #953
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/controller/AgendaAdminController.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/service/AgendaAdminService.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendaannouncement/controller/AgendaAnnouncementAdminController.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendaannouncement/service/AgendaAnnouncementAdminService.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/controller/AgendaTeamAdminController.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/service/AgendaTeamAdminService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/AgendaController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/service/AgendaService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaannouncement/controller/AgendaAnnouncementController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaannouncement/service/AgendaAnnouncementService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/AgendaProfileController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/AgendaProfileFindService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/AgendaTeamController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/controller/TicketController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/service/TicketService.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agenda/controller/AgendaAdminControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agenda/service/AgendaAdminServiceTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agendaannouncement/controller/AgendaAnnouncementAdminControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agendateam/controller/AgendaTeamAdminControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agendateam/service/AgendaTeamAdminServiceTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/controller/AgendaControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/service/AgendaServiceTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendaannouncement/controller/AgendaAnnouncementControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendaannouncement/service/AgendaAnnouncementServiceTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendaprofile/AgendaProfileControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendateam/AgendaTeamControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/ticket/TicketControllerTest.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaAnnouncementRepository.java
  gg-utils/src/main/java/gg/utils/dto/PageResponseDto.java
Labels: enhancement, refactoring

#968 🔨 [Refactoring] Agenda DateTimeFormat 변경 #967
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/controller/request/AgendaAdminUpdateReqDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/request/AgendaCreateReqDto.java
Labels: enhancement, refactoring

#970 🐛 [Bug] Agenda current Team count가 음수가 되는 버그 #969
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/request/validator/AgendaCapacityValidator.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/controller/TicketController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/controller/response/TicketCountResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/service/TicketService.java
  gg-agenda-api/src/test/java/gg/agenda/api/AgendaMockData.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendateam/AgendaTeamControllerTest.java
  gg-data/src/main/java/gg/data/agenda/Agenda.java
  gg-data/src/main/java/gg/data/agenda/AgendaTeam.java
  gg-repo/src/main/java/gg/repo/agenda/TicketRepository.java
  gg-utils/src/testFixtures/java/gg/utils/AgendaTestDataUtils.java
Labels: bug

#975 ✨ [Feature] Admin 티켓 수정 API #946
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/controller/response/AgendaTeamDetailResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/controller/response/AgendaTeamResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/ticket/controller/TicketAdminController.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/ticket/controller/request/TicketChangeAdminReqDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/ticket/service/TicketAdminService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/AgendaProfileController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/response/AttendedAgendaListResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/response/CurrentAttendAgendaListResDto.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/ticket/TicketAdminControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendaprofile/AgendaProfileControllerTest.java
  gg-data/src/main/java/gg/data/agenda/Ticket.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
Labels: enhancement

#973 ✨ [Feature] 내가 개최한 대회 조회 API 기능 구현 #952
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/response/AgendaResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/AgendaHostController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/response/HostedAgendaResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/AgendaProfileFindService.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendaprofile/AgendaHostControllerTest.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaRepository.java
  gg-utils/src/testFixtures/java/gg/utils/AgendaTestDataUtils.java
Labels: enhancement

#976 ✨ [Feature] AgendaProfile 상세조회 - 사진 및 업적 조회 기능 추가 #940
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/AgendaProfileController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/response/AgendaProfileDetailsResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/AgendaProfileFindService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/AgendaProfileService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/IntraProfileUtils.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/intraprofile/IntraAchievement.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/intraprofile/IntraImage.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/intraprofile/IntraImageVersion.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/intraprofile/IntraProfile.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/intraprofile/IntraProfileResponse.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/controller/TicketController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/service/TicketService.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendaprofile/AgendaProfileControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/ticket/TicketControllerTest.java
  gg-auth/src/main/java/gg/auth/FortyTwoAuthUtil.java
  gg-repo/src/main/java/gg/repo/agenda/TicketRepository.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
  gg-utils/src/main/java/gg/utils/exception/custom/AuthenticationException.java
Labels: enhancement, refactoring

#979 ✨ [Feature] 상황에 맞게 slack API 보내는 API 작성 #971
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/controller/AgendaTeamAdminController.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/service/AgendaTeamAdminService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/AgendaController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/service/AgendaService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaannouncement/controller/AgendaAnnouncementController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaannouncement/service/AgendaAnnouncementService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/AgendaTeamController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
  gg-agenda-api/src/main/java/gg/agenda/api/utils/AgendaSlackService.java
  gg-agenda-api/src/main/java/gg/agenda/api/utils/SnsMessageUtil.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agendateam/controller/AgendaTeamAdminControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendateam/AgendaTeamControllerTest.java
  gg-data/src/main/java/gg/data/agenda/AgendaTeam.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaTeamProfileRepository.java
Labels: enhancement

#981 ✨ [Feature] Auth관련된 부분 Cookie삭제하는 로직 추가 #980
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/AgendaProfileController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/IntraProfileUtils.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agenda/controller/AgendaAdminControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendaprofile/AgendaProfileControllerTest.java
  gg-auth/src/main/java/gg/auth/FortyTwoAuthUtil.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
Labels: enhancement

#982 ✨ [Feature] Admin 티켓 조회 API #945
  gg-admin-repo/src/main/java/gg/admin/repo/agenda/TicketAdminRepository.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/service/AgendaAdminService.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/ticket/controller/TicketAdminController.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/ticket/controller/response/TicketFindResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/ticket/service/TicketAdminFindService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/service/AgendaService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/controller/TicketController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/service/TicketService.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/ticket/TicketAdminControllerTest.java
Labels: enhancement

#985 🐛 [Bug] GET /agenda/team/my 내 팀 정보 조회에서 NonUniqueResultException 발생 #983
  gg-admin-repo/src/main/java/gg/admin/repo/agenda/AgendaTeamProfileAdminRepository.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/service/AgendaTeamAdminService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/service/AgendaService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/controller/AgendaControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/service/AgendaServiceTest.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaTeamProfileRepository.java
Labels: bug

#990 🔨 [Refactoring] Agenda History 조회시 CONFIRM 상태 추가 #988
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/service/AgendaService.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/service/AgendaServiceTest.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaRepository.java
Labels: enhancement, refactoring
