Repository 42organization/42gg.server.dev.v2, pull requests merged in 2024-09, with the labels that each got.

#989 🔨 [Refactoring] agenda api 쿼리 조회 성능 개선 #986
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/AgendaProfileFindService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
  gg-data/src/main/java/gg/data/agenda/AgendaTeam.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaRepository.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaTeamProfileRepository.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaTeamRepository.java
Labels: enhancement, refactoring

#995 ✨ [Feature] 팀원 나가기와 팀장 나가기 API 분리 #993
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/AgendaTeamController.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendateam/AgendaTeamControllerTest.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
Labels: enhancement, test

#994 🔨 [Refactoring] 진행중 대회 전체조회 API 분리 #992
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/AgendaController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/service/AgendaService.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/controller/AgendaControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/service/AgendaServiceTest.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaRepository.java
Labels: enhancement, refactoring

#991 ✨ [Feature] PosterImage 수정시 사용 여부를 알기위한 db table 추가 #984
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/service/AgendaAdminService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/service/AgendaService.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agenda/controller/AgendaAdminControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agenda/service/AgendaAdminServiceTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/controller/AgendaControllerTest.java
  gg-data/src/main/java/gg/data/agenda/AgendaPosterImage.java
  gg-pingpong-api/src/main/resources/db/migration/V3__agenda.sql
  gg-repo/src/main/java/gg/repo/agenda/AgendaPosterImageRepository.java
  gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaPosterImageFixture.java
Labels: enhancement

#997 🐛 [Bug] 포스터 이미지 없이 보내도 0바이트짜리 포스터 이미지가 생성되는 버그 #996
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/service/AgendaAdminService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/service/AgendaService.java
Labels: bug

#999 ✨ [Feature] Agenda 조회 전체 정렬 기준 수정 #998
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/AgendaController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/service/AgendaService.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/controller/AgendaControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/service/AgendaServiceTest.java
Labels: enhancement

#1001 🐛 [Bug] Agenda Confirm 상태 팀 조회 안되는 버그 #1000
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaTeamRepository.java
Labels: bug

#1003 ✨ [Feature] AgendaProfile이 없는 유저 검색시 구분을 위해 함수 분리 #1002
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/AgendaProfileController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/response/AgendaProfileDetailsResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/response/IntraProfileResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/IntraProfileUtils.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/intraprofile/IntraProfile.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/intraprofile/IntraProfileResponse.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/service/AgendaServiceTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendaprofile/AgendaProfileControllerTest.java
  gg-auth/src/main/java/gg/auth/FortyTwoAuthUtil.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
Labels: bug, enhancement

#1005 🐛 [Bug] AgendaTeamAdmin에서 cancel 상태로 변경시에 Confirm 팀일경우 currentTeam이 줄어들지 않는 버그 발생 #1004
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/service/AgendaTeamAdminService.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agendateam/controller/AgendaTeamAdminControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agendateam/service/AgendaTeamAdminServiceTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/service/AgendaServiceTest.java
  gg-data/src/main/java/gg/data/agenda/Agenda.java
  gg-data/src/main/java/gg/data/agenda/AgendaTeam.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
  gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaFixture.java
Labels: bug, enhancement

#1007 🐛 [Bug] AdminTeamUpdate시 팀장 비교 로직 수정 #1006
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/service/AgendaTeamAdminService.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agendateam/controller/AgendaTeamAdminControllerTest.java
Labels: bug

#1009 🐛 [Bug] TicketSetup 유무 확인하는 로직 전부 False로 나가는 버그 발생 #1008
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/AgendaProfileController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/controller/TicketController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/controller/response/TicketCountResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/service/TicketService.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/ticket/TicketControllerTest.java
  gg-repo/src/main/java/gg/repo/agenda/TicketRepository.java
Labels: bug

#1011 ✨ [Feature] 7기 README 업데이트 #1010
  README.md
  codecov.yml
Labels: documentation

#1012 ✨ [Feature] 7기 README 업데이트 #1010
  README.md
Labels: documentation

#1015 🐛 [Bug] 프론트와 백엔드간 URL 주소 다름으로 인한 슬랙 메세지 오류 수정 #1014
  gg-agenda-api/src/main/java/gg/agenda/api/utils/AgendaSlackService.java
  gg-agenda-api/src/main/java/gg/agenda/api/utils/SnsMessageUtil.java
Labels: bug
