Repository 42organization/42gg.server.dev.v2, pull requests merged in 2024-07, with the labels that each got.

#865 ✨ [Feature] agenda, agenda_announcement Entity 작성
  gg-data/src/main/java/gg/data/agenda/Agenda.java
  gg-data/src/main/java/gg/data/agenda/AgendaAnnouncement.java
Labels: enhancement

#867 ✨ [Feature] agenda_profile, ticket Entity 작성
  gg-data/src/main/java/gg/data/agenda/AgendaProfile.java
  gg-data/src/main/java/gg/data/agenda/Ticket.java
Labels: enhancement

#868 ✨ [Feature] Module 사전작업
  build.gradle
  gg-agenda-api/build.gradle
  gg-agenda-api/src/main/java/gg/agenda/GgAgendaApiApplication.java
  gg-agenda-api/src/test/java/gg/agenda/GgAgendaApiApplicationTests.java
  gg-data/src/main/java/gg/data/agenda/Agenda.java
  gg-data/src/main/java/gg/data/agenda/AgendaAnnouncement.java
  gg-data/src/main/java/gg/data/agenda/AgendaProfile.java
  gg-data/src/main/java/gg/data/agenda/AgendaTeam.java
  gg-data/src/main/java/gg/data/agenda/AgendaTeamProfile.java
  gg-data/src/main/java/gg/data/agenda/Ticket.java
  gg-data/src/main/java/gg/data/agenda/type/AgendaStatus.java
  gg-data/src/main/java/gg/data/agenda/type/AgendaTeamStatus.java
  gg-data/src/main/java/gg/data/agenda/type/Coalition.java
  gg-data/src/main/java/gg/data/agenda/type/Location.java
  gg-pingpong-api/src/main/resources/db/migration/V3__agenda.sql
  gg-repo/src/main/java/gg/repo/agenda/AgendaAnnouncementRepository.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaProfileRepository.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaRepository.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaTeamProfileRepository.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaTeamRepository.java
  gg-repo/src/main/java/gg/repo/agenda/TicketRepository.java
  settings.gradle
Labels: enhancement

#870 869 refactoring 멀티 모듈 의존성 추가 및 엔티티 수정
  build.gradle
  gg-agenda-api/src/main/java/gg/agenda/GgAgendaApiApplication.java
  gg-agenda-api/src/test/java/gg/agenda/GgAgendaApiApplicationTests.java
  gg-agenda-api/src/test/resources/application.yml
  gg-data/src/main/java/gg/data/agenda/Agenda.java
  gg-data/src/main/java/gg/data/agenda/AgendaTeam.java
  gg-pingpong-api/src/main/java/gg/PingpongApiApplication.java
Labels: enhancement, refactoring

#871 ✨ [Feature] #857 Agenda 상세 조회 API
  gg-agenda-api/src/main/java/gg/agenda/GgAgendaApiApplication.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/AgendaController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/dto/AgendaResponseDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/service/AgendaService.java
  gg-agenda-api/src/test/java/gg/agenda/GgAgendaApiApplicationTests.java
  gg-agenda-api/src/test/java/gg/agenda/api/AgendaMockData.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/controller/AgendaControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/service/AgendaServiceTest.java
  gg-data/src/main/java/gg/data/agenda/Agenda.java
  gg-data/src/main/java/gg/data/agenda/AgendaProfile.java
  gg-data/src/main/java/gg/data/agenda/AgendaTeam.java
  gg-data/src/main/java/gg/data/agenda/AgendaTeamProfile.java
  gg-data/src/main/java/gg/data/agenda/Ticket.java
  gg-pingpong-api/src/main/resources/db/migration/V3__agenda.sql
  gg-repo/src/main/java/gg/repo/agenda/AgendaAnnouncementRepository.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaRepository.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
  gg-utils/src/main/java/gg/utils/exception/custom/ForbiddenException.java
  gg-utils/src/main/java/gg/utils/exception/custom/InvalidParameterException.java
  gg-utils/src/main/java/gg/utils/exception/custom/NotExistException.java
Labels: enhancement

#873 ✨ [Feature] #858 Agenda 현황 전체 조회 API
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/AgendaController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/dto/AgendaResponseDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/dto/AgendaSimpleResponseDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/service/AgendaService.java
  gg-agenda-api/src/test/java/gg/agenda/api/AgendaMockData.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/controller/AgendaControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/controller/dto/AgendaSimpleResponseDtoTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/service/AgendaServiceTest.java
  gg-data/src/main/java/gg/data/agenda/Agenda.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaRepository.java
Labels: enhancement

#874 ✨ [Feature] Team 생성하기 API
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/service/AgendaService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/AgendaTeamController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/request/TeamCreateReqDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/response/TeamCreateResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
  gg-agenda-api/src/test/java/gg/agenda/api/AgendaMockData.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendateam/AgendaTeamControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/service/AgendaServiceTest.java
  gg-data/src/main/java/gg/data/agenda/Agenda.java
  gg-data/src/main/java/gg/data/agenda/AgendaAnnouncement.java
  gg-data/src/main/java/gg/data/agenda/AgendaProfile.java
  gg-data/src/main/java/gg/data/agenda/AgendaTeam.java
  gg-data/src/main/java/gg/data/agenda/AgendaTeamProfile.java
  gg-data/src/main/java/gg/data/agenda/Ticket.java
  gg-pingpong-api/src/main/resources/db/migration/V3__agenda.sql
  gg-repo/src/main/java/gg/repo/agenda/AgendaProfileRepository.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaRepository.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaTeamProfileRepository.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaTeamRepository.java
  gg-repo/src/main/java/gg/repo/agenda/TicketRepository.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
  gg-utils/src/main/java/gg/utils/exception/custom/BusinessException.java
  gg-utils/src/main/java/gg/utils/exception/custom/DuplicationException.java
Labels: enhancement, test

#875 ✨ [Feature] #859 Agenda 생성하기 API
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/AgendaController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/dto/AgendaCreateDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/dto/AgendaKeyResponseDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/service/AgendaService.java
  gg-agenda-api/src/test/java/gg/agenda/api/AgendaMockData.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/controller/AgendaControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/controller/dto/AgendaCreateDtoTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/controller/dto/AgendaSimpleResponseDtoTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/service/AgendaServiceTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/controller/AgendaControllerTest.java
  gg-data/src/main/java/gg/data/agenda/Agenda.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
Labels: enhancement

#877 ✨ [Feature] 개인 상세 조회 API
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/AgendaProfileController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/response/AgendaProfileDetailsResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/AgendaProfileFindService.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendaprofile/AgendaProfileControllerTest.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/global/config/SwaggerConfig.java
  gg-repo/src/main/java/gg/repo/agenda/TicketRepository.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
Labels: enhancement

#876 ✨ [Feature] #872 Auth 받아올 때 AgendaProfile 작성
  build.gradle
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/AgendaTeamController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/request/TeamCreateReqDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
  gg-agenda-api/src/test/java/gg/agenda/api/AgendaMockData.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendateam/AgendaTeamControllerTest.java
  gg-data/src/main/java/gg/data/agenda/AgendaProfile.java
  gg-data/src/main/java/gg/data/agenda/AgendaTeamProfile.java
  gg-data/src/main/java/gg/data/agenda/Ticket.java
  gg-data/src/main/java/gg/data/agenda/type/Coalition.java
  gg-data/src/main/java/gg/data/agenda/type/Location.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/global/security/info/OAuthUserInfo.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/global/security/info/impl/FortyTwoOAuthUserInfo.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/global/security/info/impl/KakaoOAuthUserInfo.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/global/security/service/CustomOAuth2UserService.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/global/utils/external/ApiUtil.java
  gg-pingpong-api/src/main/resources/db/migration/V3__agenda.sql
Labels: bug, enhancement

#878 ✨ [Feature] #860 지난 Agenda 조회 API
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/AgendaController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/service/AgendaService.java
  gg-agenda-api/src/test/java/gg/agenda/api/AgendaMockData.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/controller/AgendaControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/service/AgendaServiceTest.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaRepository.java
Labels: enhancement

#881 🔨 [Refactoring] 6th README update
  README.md
Labels: refactoring

#879 ✨ [Feature] Team 상세조회 API #841
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/AgendaTeamController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/request/TeamCreateReqDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/request/TeamDetailsReqDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/response/TeamCreateResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/response/TeamDetailsResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/response/TeamMateDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
  gg-agenda-api/src/test/java/gg/agenda/api/AgendaMockData.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendateam/AgendaTeamControllerTest.java
  gg-data/src/main/java/gg/data/agenda/AgendaProfile.java
  gg-pingpong-api/src/main/java/gg/pingpong/api/global/security/service/CustomOAuth2UserService.java
  gg-pingpong-api/src/main/resources/db/migration/V3__agenda.sql
  gg-repo/src/main/java/gg/repo/agenda/AgendaTeamProfileRepository.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaTeamRepository.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
Labels: enhancement, test

#882 ✨ [Feature] 내 Team 간단조회 API #842
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/AgendaTeamController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/response/MyTeamSimpleResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendateam/AgendaTeamControllerTest.java
Labels: enhancement, test

#883 ✨ [Feature] #861 Agenda 종료 확정하기 API
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/AgendaController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/request/AgendaConfirmReqDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/request/AgendaCreateReqDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/request/AgendaTeamAwardDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/response/AgendaKeyResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/response/AgendaResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/response/AgendaSimpleResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/service/AgendaService.java
  gg-agenda-api/src/test/java/gg/agenda/api/AgendaMockData.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/controller/AgendaControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/controller/dto/AgendaCreateReqDtoTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/controller/dto/AgendaSimpleResDtoTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/service/AgendaServiceTest.java
  gg-data/src/main/java/gg/data/agenda/Agenda.java
  gg-data/src/main/java/gg/data/agenda/AgendaTeam.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaTeamRepository.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
Labels: enhancement, refactoring

#884 ✨ [Feature] Team 확정하기 API #844
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/AgendaTeamController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/request/TeamKeyReqDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
  gg-agenda-api/src/test/java/gg/agenda/api/AgendaMockData.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendateam/AgendaTeamControllerTest.java
  gg-data/src/main/java/gg/data/agenda/Agenda.java
  gg-data/src/main/java/gg/data/agenda/AgendaTeam.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
Labels: enhancement, test

#890 ✨ [Feature] #886 Admin 대회 전체 조회하기
  gg-admin-repo/src/main/java/gg/admin/repo/agenda/AgendaAdminRepository.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/controller/AgendaAdminController.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/controller/response/AgendaAdminResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/service/AgendaAdminService.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agenda/controller/AgendaAdminControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agenda/service/AgendaAdminServiceTest.java
Labels: enhancement

#892 ✨ [Feature] Team 취소하기 API #845
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/AgendaProfileFindService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/AgendaTeamController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/request/TeamCreateReqDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/response/TeamKeyResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/service/TicketService.java
  gg-agenda-api/src/test/java/gg/agenda/api/AgendaMockData.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendateam/AgendaTeamControllerTest.java
  gg-data/src/main/java/gg/data/agenda/Agenda.java
  gg-data/src/main/java/gg/data/agenda/AgendaTeam.java
  gg-data/src/main/java/gg/data/agenda/AgendaTeamProfile.java
  gg-data/src/main/java/gg/data/agenda/Ticket.java
  gg-pingpong-api/src/main/resources/db/migration/V3__agenda.sql
  gg-repo/src/main/java/gg/repo/agenda/TicketRepository.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
Labels: enhancement, test

#893 ✨ [Feature] 모집중인 팀 리스트 전체 조회 API #847
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/AgendaTeamController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/request/TeamCreateReqDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/response/OpenTeamResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
  gg-agenda-api/src/test/java/gg/agenda/api/AgendaMockData.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendateam/AgendaTeamControllerTest.java
  gg-data/src/main/java/gg/data/agenda/AgendaTeam.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaTeamRepository.java
Labels: enhancement, test

#891 ✨ [Feature] #853 개인 프로필 변경 API
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/AgendaProfileController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/request/AgendaProfileChangeReqDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/AgendaProfileFindService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/AgendaProfileService.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendaprofile/AgendaProfileControllerTest.java
  gg-data/src/main/java/gg/data/agenda/AgendaProfile.java
Labels: enhancement

#894 ✨ [Feature] Admin 대회 수정 및 삭제하기 #887
  gg-admin-repo/src/main/java/gg/admin/repo/agenda/AgendaAdminRepository.java
  gg-admin-repo/src/main/java/gg/admin/repo/agenda/AgendaTeamAdminRepository.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/controller/AgendaAdminController.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/controller/request/AgendaAdminUpdateReqDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/service/AgendaAdminService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/request/AgendaCreateReqDto.java
  gg-agenda-api/src/test/java/gg/agenda/api/AgendaMockData.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agenda/controller/AgendaAdminControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agenda/service/AgendaAdminServiceTest.java
  gg-data/src/main/java/gg/data/agenda/Agenda.java
  gg-data/src/main/java/gg/data/agenda/type/Location.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
Labels: enhancement

#895 ✨ [Feature] 확정된 팀 리스트 전체 조회 API #848
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/AgendaTeamController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/response/ConfirmTeamResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendateam/AgendaTeamControllerTest.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaTeamProfileRepository.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaTeamRepository.java
Labels: enhancement, test

#903 ✨ [Feature] 팀 참가하기 API #849
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/AgendaTeamController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
  gg-agenda-api/src/test/java/gg/agenda/api/AgendaMockData.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendateam/AgendaTeamControllerTest.java
  gg-data/src/main/java/gg/data/agenda/Agenda.java
  gg-data/src/main/java/gg/data/agenda/AgendaTeam.java
  gg-data/src/main/java/gg/data/agenda/AgendaTeamProfile.java
  gg-pingpong-api/src/main/resources/db/migration/V3__agenda.sql
  gg-repo/src/main/java/gg/repo/agenda/AgendaTeamProfileRepository.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
  gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaAnnouncementFixture.java
  gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaFixture.java
  gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaTeamFixture.java
  gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaTeamProfileFixture.java
  gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/TicketFixture.java
Labels: enhancement, test

#900 ✨ [Feature] Agenda isRanking 필드 추가 #899
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/response/AgendaResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/response/AgendaSimpleResDto.java
Labels: enhancement

#897 ✨ [Feature] Admin 공지사항 전체 조회하기 #888
  gg-admin-repo/src/main/java/gg/admin/repo/agenda/AgendaAnnouncementAdminRepository.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/controller/AgendaAdminController.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendaannouncement/controller/AgendaAnnouncementAdminController.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendaannouncement/controller/response/AgendaAnnouncementAdminResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendaannouncement/service/AgendaAnnouncementAdminService.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agendaannouncement/controller/AgendaAnnouncementAdminControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agendaannouncement/service/AgendaAnnouncementAdminServiceTest.java
  gg-utils/src/testFixtures/java/gg/utils/AgendaTestDataUtils.java
Labels: enhancement

#904 ✨ [Feature] Admin 공지사항 수정 및 삭제하기 #889
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendaannouncement/controller/AgendaAnnouncementAdminController.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendaannouncement/controller/request/AgendaAnnouncementAdminUpdateReqDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendaannouncement/service/AgendaAnnouncementAdminService.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agendaannouncement/controller/AgendaAnnouncementAdminControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agendaannouncement/service/AgendaAnnouncementAdminServiceTest.java
  gg-data/src/main/java/gg/data/agenda/AgendaAnnouncement.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
Labels: enhancement

#906 ✨ [Feature] 팀 내용 수정하기 API #850
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/AgendaTeamController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/request/TeamUpdateReqDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendateam/AgendaTeamControllerTest.java
  gg-data/src/main/java/gg/data/agenda/Agenda.java
  gg-data/src/main/java/gg/data/agenda/AgendaTeam.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaTeamProfileRepository.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
  gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaTeamFixture.java
  gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaTeamProfileFixture.java
Labels: enhancement, test

#907 ✨ [Feature] Agenda 확정과 종료 분리 #905
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/AgendaController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/request/AgendaAwardsReqDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/request/AgendaCreateReqDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/request/AgendaTeamAward.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/service/AgendaService.java
  gg-agenda-api/src/test/java/gg/agenda/api/AgendaMockData.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agenda/controller/AgendaAdminControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agenda/service/AgendaAdminServiceTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/controller/AgendaControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/service/AgendaServiceTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendateam/AgendaTeamControllerTest.java
  gg-data/src/main/java/gg/data/agenda/Agenda.java
  gg-data/src/main/java/gg/data/agenda/AgendaTeam.java
  gg-data/src/main/java/gg/data/agenda/type/AgendaStatus.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaTeamRepository.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
  gg-utils/src/testFixtures/java/gg/utils/AgendaTestDataUtils.java
  gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaFixture.java
  gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaTeamFixture.java
Labels: enhancement, refactoring

#915 🐛 [Bug] Fix TestFixture checkstyle #914
  gg-utils/src/testFixtures/java/gg/utils/AgendaTestDataUtils.java
  gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaAnnouncementFixture.java
  gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaTeamFixture.java
Labels: bug

#913 ✨ [Feature] 로그인 사용자 프로필 정보 조회 API #912
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/AgendaProfileController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/response/AgendaProfileDetailsResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/response/AgendaProfileInfoDetailsResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/AgendaProfileFindService.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendaprofile/AgendaProfileControllerTest.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaProfileRepository.java
Labels: enhancement, refactoring

#916 ✨ [Feature] 티켓 발급 시작 API #908
  gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/controller/TicketController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/service/TicketService.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/ticket/TicketControllerTest.java
  gg-data/src/main/java/gg/data/agenda/Ticket.java
  gg-repo/src/main/java/gg/repo/agenda/TicketRepository.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
  gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaProfileFixture.java
  gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/TicketFixture.java
Labels: enhancement, test

#917 ✨ [Feature] 가진 티켓 확인 API #910
  gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/controller/TicketController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/controller/response/TicketCountResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/service/TicketService.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/ticket/TicketControllerTest.java
Labels: enhancement, test

#918 ✨ [Feature] Admin AgendaTeam 전체 조회하기 #898
  gg-admin-repo/src/main/java/gg/admin/repo/agenda/AgendaTeamAdminRepository.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/controller/AgendaTeamAdminController.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/controller/response/AgendaTeamResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/service/AgendaTeamAdminService.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agendateam/controller/AgendaTeamAdminControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agendateam/service/AgendaTeamAdminServiceTest.java
Labels: enhancement

#919 ✨ [Feature] Admin AgendaTeam 상세 조회하기 #901
  gg-admin-repo/src/main/java/gg/admin/repo/agenda/AgendaTeamAdminRepository.java
  gg-admin-repo/src/main/java/gg/admin/repo/agenda/AgendaTeamProfileAdminRepository.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/controller/AgendaTeamAdminController.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/controller/request/AgendaTeamKeyReqDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/controller/response/AgendaProfileResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/controller/response/AgendaTeamDetailResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/service/AgendaTeamAdminService.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agendateam/controller/AgendaTeamAdminControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agendateam/service/AgendaTeamAdminServiceTest.java
  gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaProfileFixture.java
Labels: enhancement

#920 ✨ [Feature] 티켓 히스토리 조회 API #911
  gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/controller/TicketController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/controller/response/TicketHistoryResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/service/TicketService.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/ticket/TicketControllerTest.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaRepository.java
  gg-repo/src/main/java/gg/repo/agenda/TicketRepository.java
  gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/TicketFixture.java
Labels: enhancement, test

#923 🔨 [Refactoring] Checkstyle validation - TestFixture 추가 #922
  .github/workflows/checkstyle-validation.yml
  gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaProfileFixture.java
Labels: enhancement, refactoring

#924 ✨ [Feature] 내가 참여 중인 대회 보기 API #854
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/AgendaProfileController.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/response/CurrentAttendAgendaListResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/AgendaProfileFindService.java
  gg-agenda-api/src/test/java/gg/agenda/api/user/agendaprofile/AgendaProfileControllerTest.java
  gg-repo/src/main/java/gg/repo/agenda/AgendaTeamProfileRepository.java
Labels: enhancement

#921 ✨ [Feature] Admin AgendaTeam 수정하기 #902
  gg-admin-repo/src/main/java/gg/admin/repo/agenda/AgendaProfileAdminRepository.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/controller/AgendaTeamAdminController.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/controller/request/AgendaTeamMateReqDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/controller/request/AgendaTeamUpdateDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/controller/response/AgendaTeamDetailResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/controller/response/AgendaTeamMateResDto.java
  gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/service/AgendaTeamAdminService.java
  gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/request/AgendaTeamAward.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agendateam/controller/AgendaTeamAdminControllerTest.java
  gg-agenda-api/src/test/java/gg/agenda/api/admin/agendateam/service/AgendaTeamAdminServiceTest.java
  gg-data/src/main/java/gg/data/agenda/AgendaTeam.java
  gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaFixture.java
  gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaProfileFixture.java
  gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaTeamFixture.java
  gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaTeamProfileFixture.java
Labels: enhancement
