Repository 42organization/42gg.server.dev.v2, pull requests merged in 2025-01, with the labels that each got.

#1105 🛠️ [Refactoring] 전체일정 삭제 API 수정 - 전체일정과 연관된 개인일정 삭제 로직 변경 #1101
  gg-calendar-api/src/main/java/gg/calendar/api/user/schedule/publicschedule/controller/PublicScheduleController.java
  gg-calendar-api/src/main/java/gg/calendar/api/user/schedule/publicschedule/service/PublicScheduleService.java
  gg-calendar-api/src/test/java/gg/calendar/api/user/schedule/publicschedule/controller/PublicScheduleControllerTest.java
  gg-data/src/main/java/gg/data/calendar/PrivateSchedule.java
  gg-repo/src/main/java/gg/repo/calendar/PrivateScheduleRepository.java
Labels: refactoring

#1106 ✨ [Feature] 개인일정 삭제 API #1104
  gg-calendar-api/src/main/java/gg/calendar/api/user/schedule/privateschedule/controller/PrivateScheduleController.java
  gg-calendar-api/src/main/java/gg/calendar/api/user/schedule/privateschedule/controller/request/PrivateScheduleUpdateReqDto.java
  gg-calendar-api/src/main/java/gg/calendar/api/user/schedule/privateschedule/service/PrivateScheduleService.java
  gg-calendar-api/src/main/java/gg/calendar/api/user/schedule/publicschedule/controller/PublicScheduleController.java
  gg-calendar-api/src/main/java/gg/calendar/api/user/schedule/publicschedule/service/PublicScheduleService.java
  gg-calendar-api/src/test/java/gg/calendar/api/user/schedule/privateschedule/PrivateScheduleMockData.java
  gg-calendar-api/src/test/java/gg/calendar/api/user/schedule/privateschedule/controller/PrivateScheduleControllerTest.java
  gg-data/src/main/java/gg/data/calendar/PrivateSchedule.java
  gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
Labels: enhancement

#1122 ✨ [Feature] 전체일정 추가 42event일때 api 생성 #1121
  gg-calendar-api/src/main/java/gg/calendar/api/user/schedule/publicschedule/controller/PublicScheduleController.java
  gg-calendar-api/src/main/java/gg/calendar/api/user/schedule/publicschedule/controller/request/PublicScheduleCreateEventReqDto.java
  gg-calendar-api/src/main/java/gg/calendar/api/user/schedule/publicschedule/service/PublicScheduleService.java
  gg-calendar-api/src/test/java/gg/calendar/api/user/schedule/publicschedule/controller/PublicScheduleControllerTest.java
  gg-calendar-api/src/test/java/gg/calendar/api/user/schedule/publicschedule/controller/request/PublicScheduleCreateReqDtoTest.java
Labels: enhancement

#1124 ✨ [Feature] 전체일정 추가 job_tag일 때 API 생성 #1123
  gg-calendar-api/src/main/java/gg/calendar/api/user/schedule/publicschedule/controller/PublicScheduleController.java
  gg-calendar-api/src/main/java/gg/calendar/api/user/schedule/publicschedule/controller/request/PublicScheduleCreateJobReqDto.java
  gg-calendar-api/src/main/java/gg/calendar/api/user/schedule/publicschedule/service/PublicScheduleService.java
  gg-calendar-api/src/test/java/gg/calendar/api/user/schedule/publicschedule/controller/PublicScheduleControllerTest.java
  gg-calendar-api/src/test/java/gg/calendar/api/user/schedule/publicschedule/controller/request/PublicScheduleCreateEventReqDtoTest.java
  gg-calendar-api/src/test/java/gg/calendar/api/user/schedule/publicschedule/controller/request/PublicScheduleCreateJobReqDtoTest.java
  gg-calendar-api/src/test/java/gg/calendar/api/user/schedule/publicschedule/controller/request/PublicScheduleCreateReqDtoTest.java
Labels: enhancement

#1126 🛠️ [REFACTOR] PublicScheduleUpdate API 수정 #1107
  gg-calendar-api/src/main/java/gg/calendar/api/user/schedule/publicschedule/controller/request/PublicScheduleCreateEventReqDto.java
  gg-calendar-api/src/main/java/gg/calendar/api/user/schedule/publicschedule/controller/request/PublicScheduleCreateJobReqDto.java
  gg-calendar-api/src/main/java/gg/calendar/api/user/schedule/publicschedule/controller/request/PublicScheduleUpdateReqDto.java
  gg-calendar-api/src/main/java/gg/calendar/api/user/schedule/publicschedule/service/PublicScheduleService.java
  gg-calendar-api/src/test/java/gg/calendar/api/user/schedule/publicschedule/controller/PublicScheduleControllerTest.java
  gg-calendar-api/src/test/java/gg/calendar/api/user/schedule/publicschedule/controller/request/PublicScheduleUpdateReqDtoTest.java
Labels: refactoring, test

#1134 ✨ [Feature] 전체일정 기간조회 api 생성 및 완료 #1062
  gg-calendar-api/src/main/java/gg/calendar/api/user/schedule/publicschedule/controller/PublicScheduleController.java
  gg-calendar-api/src/main/java/gg/calendar/api/user/schedule/publicschedule/controller/response/PublicSchedulePeriodRetrieveResDto.java
  gg-calendar-api/src/main/java/gg/calendar/api/user/schedule/publicschedule/service/PublicScheduleService.java
  gg-calendar-api/src/main/java/gg/calendar/api/user/schedule/publicschedule/service/TotalScheduleService.java
  gg-calendar-api/src/test/java/gg/calendar/api/user/schedule/publicschedule/PublicScheduleMockData.java
  gg-calendar-api/src/test/java/gg/calendar/api/user/schedule/publicschedule/controller/PublicScheduleControllerTest.java
  gg-calendar-api/src/test/java/gg/calendar/api/user/schedule/publicschedule/controller/TotalSheduleControllerTest.java
  gg-calendar-api/src/test/java/gg/calendar/api/user/schedule/publicschedule/controller/response/PublicSchedulePeriodRetrieveResDtoTest.java
  gg-repo/src/main/java/gg/repo/calendar/PublicScheduleRepository.java
Labels: enhancement

#1138 ✨ [Feature] 전체일정 개인일정에 추가 api 작성 #1064
  gg-calendar-api/src/main/java/gg/calendar/api/user/schedule/publicschedule/controller/PublicScheduleController.java
  gg-calendar-api/src/main/java/gg/calendar/api/user/schedule/publicschedule/controller/TotalScheduleController.java
  gg-calendar-api/src/main/java/gg/calendar/api/user/schedule/publicschedule/service/PublicScheduleService.java
  gg-calendar-api/src/main/java/gg/calendar/api/user/schedule/publicschedule/service/TotalScheduleService.java
  gg-calendar-api/src/test/java/gg/calendar/api/user/schedule/publicschedule/controller/PublicScheduleControllerTest.java
  gg-calendar-api/src/test/java/gg/calendar/api/user/schedule/publicschedule/controller/response/PublicScheduleDetailRetrieveResDtoTest.java
  gg-repo/src/main/java/gg/repo/calendar/ScheduleGroupRepository.java
Labels: enhancement, test

#1142 🛠️ [Refactoring] PublicScheduleDto에 누락된 status정보 추가 #1141
  gg-calendar-api/src/main/java/gg/api42/ApiClient.java
  gg-calendar-api/src/main/java/gg/calendar/api/user/schedule/publicschedule/controller/response/PublicScheduleDetailRetrieveResDto.java
  gg-calendar-api/src/main/java/gg/calendar/api/user/schedule/publicschedule/controller/response/PublicSchedulePeriodRetrieveResDto.java
  gg-repo/src/main/java/gg/repo/calendar/ScheduleGroupRepository.java
Labels: refactoring
